import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readIndexHtml(): string {
  return fs.readFileSync(path.join(process.cwd(), 'web/index.html'), 'utf-8')
}

function extractAside(html: string, className: string): string {
  const match = html.match(new RegExp(`<aside class="${className}">([\\s\\S]*?)</aside>`))
  return match?.[1] || ''
}

function extractFunction(source: string, name: string): string {
  const start = source.indexOf(`function ${name}`)
  if (start < 0) return ''
  const next = source.indexOf('\nfunction ', start + 1)
  return source.slice(start, next < 0 ? undefined : next)
}

describe('frontend layout', () => {
  it('removes runtime user config injection and reserves the rails for game state', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const leftRail = extractAside(html, 'left-rail')
    const rightRail = extractAside(html, 'right-rail')

    expect(html).not.toContain('id="moduleConfigButton"')
    expect(html).not.toContain('id="moduleConfigDialog"')
    expect(html).not.toContain('id="moduleList"')
    expect(html).not.toContain('注入配置')

    expect(leftRail).toContain('全局流水线')
    expect(leftRail).toContain('id="debugOutput"')
    expect(css).toContain('.left-rail {\n  grid-template-rows: minmax(0, 1fr);')

    expect(rightRail).not.toContain('AI 速度评估')
    expect(rightRail).not.toContain('id="statsView"')
    expect(rightRail).not.toContain('stats-panel')
    expect(css).toContain('.right-rail {\n  grid-template-rows: minmax(0, 1fr) minmax(0, 1fr);')
    expect(rightRail).not.toContain('id="debugOutput"')

    expect(appJs).not.toContain('loadModules')
    expect(appJs).not.toContain('/api/modules')
    expect(appJs).not.toContain('allModules')
    expect(appJs).not.toContain('userModules:')
    expect(appJs).not.toContain('moduleEnabled')
    expect(css).not.toContain('.module-config-dialog')
    expect(css).not.toContain('.module-list')
    expect(css).not.toContain('.module-item')
  })

  it('exposes a regenerate button for the latest turn', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="regenerateButton"')
    expect(appJs).toContain('lastTurnSnapshot')
    expect(appJs).toContain('function regenerateLastTurn()')
  })

  it('can roll back the latest turn once after success or failure', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="rollbackTurnButton"')
    expect(html).toContain('回退上一轮')
    expect(appJs).toContain('rollbackTurnButton')
    expect(appJs).toContain('function rollbackUnfinishedTurn')
    expect(appJs).toContain('const canRollback = Boolean(normalizeTurnSnapshot(state.lastTurnSnapshot))')
    expect(appJs).toContain('restoreTurnSnapshot(snapshot)')
    expect(appJs).toContain('state.lastTurnSnapshot = null')
    expect(appJs).toContain("status: 'rolled_back'")
    expect(appJs).toContain('本次回退快照已清空，不能继续向前回退')
    expect(appJs).toContain('els.playerInput.value = snapshot.playerInput')
  })

  it('aborts stale generation streams before they can keep mutating the active story', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('let activeStreamController = null')
    expect(appJs).toContain('function beginActiveStream')
    expect(appJs).toContain('function abortActiveStream')
    expect(appJs).toContain('signal: streamController.signal')
    expect(appJs).toContain('if (streamController.signal.aborted) return')
    expect(appJs).toContain('abortActiveStream()')
  })

  it('shows full runtime prompts for every pipeline task', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).toContain('id="promptPreviewButton"')
    expect(html).toContain('id="promptPreviewDialog"')
    expect(html).toContain('id="promptPreviewList"')
    expect(html).toContain('展示当前存档拼接后的实际发送 prompt')
    expect(html).not.toContain('system / user')
    expect(appJs).toContain('function openPromptPreview')
    expect(appJs).toContain("fetch('/api/prompt-preview'")
    expect(appJs).toContain('function latestPlayerInputForPromptPreview')
    expect(appJs).toContain('function isSyntheticPromptInput')
    expect(appJs).toContain('const payload = buildGenerateRequestPayload(latestPlayerInputForPromptPreview())')
    expect(serverTs).toContain("const playerInput = String(input.playerInput || '').trim()")
    expect(serverTs).not.toContain("|| '查看当前 prompt 拼接。'")
    expect(serverTs).toContain('function isSyntheticPromptInput')
    expect(serverTs).toContain("const playerInput = isSyntheticPromptInput(rawPlayerInput) ? '' : rawPlayerInput")
    expect(serverTs).toContain('input.recentTurns')
    expect(serverTs).toContain('filter(turn => !isSyntheticPromptInput(turn.content))')
    expect(appJs).toContain('function renderPromptPreview')
    expect(appJs).toContain('<textarea readonly spellcheck="false">${escapeHtml(item.user')
    expect(appJs).not.toContain('${escapeHtml(item.system')
    expect(appJs).not.toContain('System ${Number(item.systemLength')
    expect(serverTs).toContain("url.pathname === '/api/prompt-preview'")
    expect(serverTs).toContain('function buildPromptPreview')
    expect(serverTs).toContain('userLength: item.user.length')
    expect(serverTs).not.toContain('systemLength: item.system.length')
    expect(serverTs).toContain("task: 'Initializer'")
    expect(serverTs).toContain('Initializer 真实输入只来自故事库导入的原始材料')
    expect(serverTs).toContain("task: 'Director'")
    expect(serverTs).toContain("task: 'Narrator'")
    expect(serverTs).toContain("task: 'Postprocess'")
    expect(serverTs).not.toContain("task: 'LongRangeDirector'")
    expect(css).toContain('.prompt-preview-dialog')
    expect(css).toContain('.prompt-preview-item textarea')
  })

  it('lets Infron reasoning effort be selected from the frontend', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="infronReasoningSelect"')
    expect(html).toContain('默认（不指定）')
    expect(html).toContain('<option value="medium">medium</option>')
    expect(appJs).toContain('const infronReasoningStorageKey')
    expect(appJs).toContain('function getInfronReasoningEffort')
    expect(appJs).toContain('function setInfronReasoningEffort')
    expect(appJs).toContain('reasoningEffort: getRequestReasoningEffort()')
    expect(appJs).toContain("reasoningEffort: provider === 'infron' ? getInfronReasoningEffort() : ''")
  })

  it('uses manual save slots for collectible branches', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).toContain('id="saveSlotsDialog"')
    expect(html).toContain('id="saveSlotsList"')
    expect(html).toContain('收藏存档会置顶')
    expect(appJs).toContain('function saveCurrentSlot')
    expect(appJs).toContain("state: { story: deepClone(state) }")
    expect(appJs).toContain("fetch('/api/save-slots'")
    expect(appJs).toContain('function loadSaveSlot')
    expect(appJs).toContain('function toggleSaveSlotFavorite')
    expect(appJs).toContain('function deleteSaveSlot')
    expect(css).toContain('.save-slot-list')
    expect(css).toContain('.save-slot-item')
    expect(serverTs).toContain("const saveSlotsDir = path.join(saveDir, 'slots')")
    expect(serverTs).toContain("const speedRecordsDir = path.join(saveDir, 'speed-records')")
    expect(serverTs).toContain("url.pathname === '/api/save-slots'")
    expect(serverTs).toContain("url.pathname.match(/^\\/api\\/save-slots\\/([^/]+)$/)")
    expect(serverTs).toContain('function createSaveSlot')
    expect(serverTs).toContain('function updateSaveSlot')
    expect(serverTs).toContain('function deleteSaveSlot')
  })

  it('keeps the free input composer compact to leave room for reading', () => {
    const html = readIndexHtml()
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')

    expect(html).toContain('<textarea id="playerInput" rows="2"')
    expect(html).toContain('<textarea id="playerFeedback" rows="1"')
    expect(css).toContain('min-height: 52px;')
    expect(css).toContain('max-height: 118px;')
    expect(css).toContain('padding: 9px 12px;')
  })

  it('persists player feedback until the player edits or clears it', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('playerFeedback: document.querySelector(\'#playerFeedback\')')
    expect(appJs).toContain('playerFeedback: \'\'')
    expect(appJs).toContain('playerFeedback: String(raw?.playerFeedback || \'\')')
    expect(appJs).toContain('function renderPlayerFeedback')
    expect(appJs).toContain('state.playerFeedback = els.playerFeedback.value.trim()')
    expect(appJs).toContain('playerFeedback: state.playerFeedback')
    expect(appJs).toContain('const playerFeedback = els.playerFeedback.value.trim()')
    expect(appJs).toContain('playerFeedback: state.debug?.postprocessRecoveryBase?.playerFeedback || \'\'')
    expect(appJs).not.toContain('els.playerFeedback.value = \'\'')
    expect(appJs).not.toContain('state.feedbackMemory = mergeFeedbackMemory(state.feedbackMemory, playerFeedback')
  })

  it('keeps opening text visible while treating it as an evictable turn zero in recent context', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('function renderOpeningMessage')
    expect(appJs).toContain('data-message-role="opening"')
    expect(appJs).toContain('renderOpeningMessage()')
    expect(appJs).toContain('const messagesHtml = state.messages.map')
    expect(appJs).toContain('els.conversation.innerHTML = `${renderOpeningMessage()}${messagesHtml}`')
    expect(appJs).toContain('const hasOpening = Boolean(String(state.openingText || \'\').trim())')
    expect(appJs).toContain('const hasMessages = hasOpening || (Array.isArray(state.messages) && state.messages.length > 0)')
    expect(appJs).toContain('function buildOpeningRecentTurn')
    expect(appJs).toContain('role: \'assistant\'')
    expect(appJs).toContain('content: `第0轮：${opening}`')
    expect(appJs).toContain('const withOpening = openingRecentTurn ? [openingRecentTurn, ...withoutPendingUser] : withoutPendingUser')
    expect(appJs).toContain('return withOpening.slice(-11)')
    expect(appJs.indexOf('const withOpening = openingRecentTurn ? [openingRecentTurn, ...withoutPendingUser] : withoutPendingUser'))
      .toBeLessThan(appJs.indexOf('return withOpening.slice(-11)'))
    expect(appJs).toContain('return state.messages.filter(message => message.role === \'assistant\').length')
  })

  it('exposes a director control dialog for god-mode story steering', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="directorControlButton"')
    expect(html).toContain('id="directorControlDialog"')
    expect(html).toContain('id="directorPlotGoalInput"')
    expect(html).not.toContain('id="directorGuidanceInput"')
    expect(html).toContain('导演控制台')
    expect(appJs).toContain('function openDirectorControl')
    expect(appJs).toContain('function saveDirectorControl')
    expect(appJs).not.toContain('directorGuidance')
  })

  it('exposes editable story settings and story-specific director/narrator styles', () => {
    const html = readIndexHtml()
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).toContain('id="storySettingsForm"')
    expect(html).toContain('id="storyLibraryPage"')
    expect(html).toContain('class="story-library-page"')
    expect(html).not.toContain('id="storyLibraryDialog"')
    expect(html).toContain('id="storyProgramConfigInput"')
    expect(html).toContain('class="json-editor"')
    expect(html).not.toContain('id="storyWorldviewInput"')
    expect(html).not.toContain('id="storyOpeningTextInput"')
    expect(html).not.toContain('id="storyDirectorStyleInput"')
    expect(html).not.toContain('id="storyNarratorStyleInput"')
    expect(html).toContain('id="saveStorySettingsButton"')
    expect(html).toContain('id="deleteStoryAssetButton"')

    expect(css).toContain('.story-library-grid')
    expect(css).toContain('.story-library-page')
    expect(css).toContain('.library-hero')
    expect(css).not.toContain('.library-preview-panel')
    expect(css).toContain('.story-settings-form')
    expect(css).toContain('grid-template-columns: minmax(260px, 0.55fr) minmax(640px, 1.45fr)')
    expect(appJs).toContain("directorStyle: ''")
    expect(appJs).toContain("narratorStyle: ''")
    expect(appJs).toContain('directorStyle: String(raw?.directorStyle || \'\')')
    expect(appJs).toContain('narratorStyle: String(raw?.narratorStyle || \'\')')
    expect(appJs).toContain('function renderStorySettingsForm')
    expect(appJs).toContain('function saveSelectedStorySettings')
    expect(appJs).toContain('JSON.stringify(config, null, 2)')
    expect(appJs).toContain('renderAssetPreview(els.newGamePreview, asset)')
    expect(appJs).toContain('<strong>Program Config JSON</strong>')
    expect(appJs).toContain("asset.programConfig ? JSON.stringify(config, null, 2) : '未初始化，请在故事库点击初始化。'")
    expect(appJs).not.toContain('初始化人物')
    expect(appJs).not.toContain('初始化资料')
    expect(appJs).toContain('patch = parseEditableJson(els.storyProgramConfigInput.value')
    expect(appJs).toContain('function parseEditableJson')
    expect(appJs).toContain('function escapeControlCharactersInJsonStrings')
    expect(appJs).toContain("output += '\\\\n'")
    expect(appJs).toContain('function saveStoryAssetProgramConfig')
    expect(appJs).toContain('const savedConfig = await saveStoryAssetProgramConfig(asset, payload)')
    expect(appJs).toContain('Initializer 已返回 JSON，但 program-config 未落盘')
    expect(appJs).toContain('function deleteSelectedStoryAsset')
    expect(appJs).toContain('function openStoryLibraryPage')
    expect(appJs).toContain('function closeStoryLibraryPage')
    expect(appJs).toContain('els.gamePage.hidden = true')
    expect(appJs).toContain('els.storyLibraryPage.hidden = false')
    expect(appJs).toContain('await loadStoryLibrary()')
    expect(appJs).toContain('未写入本地 story 目录')
    expect(appJs).not.toContain('The imported content still remains in the current browser session')
    expect(appJs).toContain("fetch(`/api/story-assets/${encodeURIComponent(asset.id)}`, { method: 'DELETE' })")
    expect(appJs).toContain("fetch(`/api/story-assets/${encodeURIComponent(asset.id)}/program-config`")
    expect(appJs).toContain('directorStyle: state.directorStyle')
    expect(appJs).toContain('narratorStyle: state.narratorStyle')

    expect(serverTs).toContain('directorStyle?: string')
    expect(serverTs).toContain('narratorStyle?: string')
    expect(serverTs).toContain('directorStyle,')
    expect(serverTs).toContain('narratorStyle,')
    expect(serverTs).toContain("url.pathname.match(/^\\/api\\/story-assets\\/([^/]+)\\/program-config$/)")
    expect(serverTs).toContain("url.pathname.match(/^\\/api\\/story-assets\\/([^/]+)$/)")
    expect(serverTs).toContain('function deleteStoryAsset')
    expect(serverTs).toContain('故事资料未写入本地 story 目录，请重新导入后再初始化。')
    expect(serverTs).toContain('function updateStoryAssetProgramConfig')
    expect(serverTs).toContain('## 导演风格')
    expect(serverTs).toContain('## 叙事风格')
  })

  it('can test the current model provider from the toolbar', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).toContain('id="providerTestButton"')
    expect(html).toContain('连通性测试')
    expect(html).toContain('id="providerSpeedTestButton"')
    expect(html).toContain('速度测试')
    expect(html).toContain('model-selection-form')
    expect(html).toContain('api-key-form')
    expect(html).toContain('<h3>模型选择</h3>')
    expect(html).toContain('<h3>API Key</h3>')
    expect(appJs).toContain('providerTestButton: document.querySelector')
    expect(appJs).toContain('providerSpeedTestButton: document.querySelector')
    expect(appJs).toContain('function testCurrentProvider')
    expect(appJs).toContain('function testCurrentProviderSpeed')
    expect(appJs).toContain("fetch('/api/provider-test'")
    expect(appJs).toContain("fetch('/api/provider-speed-test'")
    expect(appJs).toContain('apiKey: getLocalApiKey(provider)')
    expect(appJs).toContain('连通性测试中')
    expect(appJs).toContain('速度测试中')
    expect(appJs).toContain('不可用')
    expect(appJs).toContain('renderModelTestResult')
    expect(appJs).toContain('ttftMs')
    expect(appJs).toContain('tps')
    expect(appJs).toContain("reply: '成功'")
    expect(appJs).toContain("outputTokens: '-'")
    expect(serverTs).toContain("url.pathname === '/api/provider-test'")
    expect(serverTs).toContain("url.pathname === '/api/provider-speed-test'")
    expect(serverTs).toContain('async function testProvider')
    expect(serverTs).toContain('async function testProviderSpeed')
    expect(serverTs).toContain('连通性测试。只输出：ok')
    expect(serverTs).toContain('约 1200 个汉字')
    expect(serverTs).toContain('providerConnectivityTimeoutMs')
    expect(serverTs).toContain('providerSpeedTestTimeoutMs')
  })

  it('regenerates by running the plain pipeline without cache flags', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(appJs).toContain('正在回滚并重新生成本次对话；会使用当前模型和配置完整重跑。')
    expect(appJs).not.toContain('bypassGenerationCache')
    expect(serverTs).not.toContain('bypassGenerationCache')
    expect(serverTs).not.toContain('getDirectorCacheEntry')
    expect(serverTs).not.toContain('getNarratorCacheEntry')
  })

  it('does not keep director cache fallback or emergency plans', () => {
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(serverTs).not.toContain('function isDirectorTimeoutError')
    expect(serverTs).not.toContain('cachedDirectorFallback')
    expect(serverTs).not.toContain('function buildEmergencyDirectorPlan')
    expect(serverTs).not.toContain('Director 未能及时返回，使用本地应急导演计划继续本轮。')
  })

  it('continues unfinished turns by reusing the completed director plan when available', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).toContain('继续未完成')
    expect(appJs).toContain('function continueUnfinishedTurn')
    expect(appJs).toContain("modeLabel: 'continuing'")
    expect(appJs).toContain('继续未完成：按当前状态重新执行未完成流程。')
    expect(appJs).toContain('postprocessRecoveryBase')
    expect(appJs).toContain('requestPayload')
    expect(appJs).toContain('director: director && typeof director ===')
    expect(appJs).toContain('const { apiKey, apiKeys, ...safePayload } = payload')
    expect(serverTs).toContain('director?: Record<string, unknown>')
    expect(serverTs).toContain("导演层已复用：继续未完成时沿用上一轮计划。")
    expect(serverTs).toContain("type: 'stage_skip', stage: 'director'")
    expect(appJs).not.toContain('preferEmergencyDirectorFallback')
    expect(appJs).not.toContain('function hasDirectorTimeoutDebug')
    expect(appJs).not.toContain('await regenerateLastTurn()')
  })

  it('shows the current completed turn count in the header', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="turnStatus"')
    expect(appJs).toContain('function renderTurnStatus')
    expect(appJs).toContain('function completedAssistantTurnCount')
    expect(appJs).toContain('当前第')
    expect(appJs).toContain('正在生成第')
  })

  it('supports showing edited text before background postprocess completes', () => {
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(serverTs).toContain("type: 'visible_text'")
    expect(appJs).toContain('function applyVisibleTextEvent')
    expect(appJs).toContain("event.type === 'visible_text'")
    expect(appJs).toContain('Postprocess 会进入独立队列，不阻塞下一轮输入')
  })

  it('anchors visible text at the latest turn start instead of the bottom', () => {
    const html = readIndexHtml()
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="jumpTurnStartButton"')
    expect(html).toContain('id="jumpLatestButton"')
    expect(css).toContain('.reading-jump-bar')
    expect(appJs).toContain('function isConversationNearBottom')
    expect(appJs).toContain('function scrollToLatestAssistantStart')
    expect(appJs).toContain('function scrollToConversationBottom')
    expect(appJs).toContain('data-message-index')
    expect(appJs).toContain("renderConversation({ scrollTarget: 'latest-assistant-start' })")
    expect(appJs).toContain("scrollTarget === 'latest-assistant-start'")
    expect(appJs).toContain("scrollTarget === 'bottom'")
    expect(appJs).toContain('function renderReadingJumpControls')
  })

  it('does not rerender the conversation when background postprocess completes', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('function persistPostprocessResult')
    expect(appJs).toContain('renderPostprocessSideEffects')
    expect(appJs).toContain('renderStatusPanel()')
    expect(appJs).toContain('renderStoryTracking()')
    expect(appJs).toContain('renderOptions()')
    expect(appJs).not.toContain('renderStats()')
    expect(appJs).toContain('renderDebug()')
    expect(appJs).toContain('applyPostprocess(payload)\n    persistPostprocessResult()')
    expect(appJs).not.toContain('applyPostprocess(payload)\n    persistAndRender()')
    expect(appJs).not.toContain('persistPostprocessResult()\n    persistPostprocessResult()')
    expect(appJs).toContain('let persistController = null')
    expect(appJs).toContain('if (persistController) persistController.abort()')
    expect(appJs).toContain('signal: persistController.signal')
  })

  it('removes editor refinement from the runtime pipeline', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).not.toContain('id="refineToggle"')
    expect(html).not.toContain('开启全文精修')
    expect(appJs).not.toContain('enableEditor')
    expect(serverTs).not.toContain('input.enableEditor')
    expect(serverTs).not.toContain("readPrompt('editor/prompt.md')")
    expect(serverTs).not.toContain("stage: 'editor'")
    expect(serverTs).toContain("stage: 'narrator'")
    expect(serverTs).toContain("pipelineMode: 'narrator+postprocess-queued'")
  })

  it('removes AI speed stats panel and keeps timing in the pipeline log', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')

    expect(html).not.toContain('id="statsView"')
    expect(appJs).not.toContain('function updateRuntimeStatsFromPipeline')
    expect(appJs).not.toContain('function buildClientRuntimeStats')
    expect(appJs).not.toContain('payload.metrics || buildClientRuntimeStats')
    expect(appJs).not.toContain('statsView')
    expect(appJs).toContain('function formatPipelineElapsed')
    expect(appJs).toContain('function formatPipelineLog')
    expect(appJs).toContain('耗时 ${formatPipelineMs')
    expect(html).toContain('class="pipeline-model-grid"')
    expect(appJs).toContain('renderPipelineModelGrid(model, pipelineModels)')
    expect(css).toContain('.pipeline-model-card')
  })

  it('queues postprocess independently from the next player turn', () => {
    const html = readIndexHtml()
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="retryStageButton"')
    expect(html).toContain('继续未完成')
    expect(serverTs).toContain("url.pathname === '/api/postprocess-stream'")
    expect(serverTs).toContain('async function runPostprocess')
    expect(appJs).toContain('function continueUnfinishedTurn')
    expect(appJs).toContain('function enqueuePostprocessJob')
    expect(appJs).toContain('async function processPostprocessQueue')
    expect(appJs).toContain('postprocessQueueRunning')
    expect(appJs).toContain('postprocessQueue: []')
    expect(appJs).toContain('function renderRetryStageButton')
    expect(appJs).toContain('pendingPostprocess')
    expect(appJs).toContain('storyId: state.id')
    expect(appJs).toContain('storyName: state.name')
    expect(appJs).toContain('markRunningPipelineStageError')
    expect(appJs).toContain('els.sendButton.disabled = isBusy')
    expect(appJs).not.toContain('完成前不能发送下一轮')
    expect(appJs).not.toContain('await regenerateLastTurn()')
  })

  it('renders character status as raw JSON', () => {
    const html = readIndexHtml()
    const css = fs.readFileSync(path.join(process.cwd(), 'web/styles.css'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="statusPanelView"')
    expect(html).not.toContain('id="characterList"')
    expect(html).not.toContain('id="addCharacterButton"')
    expect(appJs).toContain('<pre class="status-json">${escapeHtml(JSON.stringify(state.statusState || {}, null, 2))}</pre>')
    expect(appJs).not.toContain('function renderCharacters')
    expect(appJs).not.toContain('function characterInput')
    expect(appJs).not.toContain('function parseStatusPanelPersons')
    expect(appJs).not.toContain('function renderStatusPersonCard')
    expect(appJs).not.toContain('<details class="status-person-card"')
    expect(appJs).not.toContain('class="status-card"')
    expect(appJs).not.toContain('class="status-schema"')
    expect(appJs).not.toContain('追踪：${state.statusSubject}')
    expect(appJs).not.toContain('每轮后处理更新')
    expect(css).toContain('.status-json')
    expect(css).not.toContain('.status-card')
    expect(css).not.toContain('.status-schema')
    expect(css).not.toContain('.status-people')
    expect(css).not.toContain('.status-person-card')
    expect(css).not.toContain('.character-item')
    expect(css).not.toContain('.character-detail')
  })

  it('adds status patch names to the tracked roster even when rosterPatch is empty', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const mergeRoster = extractFunction(appJs, 'mergeStatusRoster')

    expect(mergeRoster).toContain('Object.keys(statePatch)')
    expect(mergeRoster).toContain('...patchNames')
    expect(appJs).toContain('state.statusRoster = mergeStatusRoster(state.statusRoster, statusPatch.statusRosterPatch, state.characters, statusPatch.statusStatePatch)')
  })

  it('applies full status state returned by postprocess final payload', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const applyPostprocess = extractFunction(appJs, 'applyPostprocess')

    expect(applyPostprocess).toContain('const statusPatch = payload.postprocess')
    expect(applyPostprocess).toContain('if (Array.isArray(payload.statusRoster))')
    expect(applyPostprocess).toContain('state.statusRoster = normalizeStatusRoster(payload.statusRoster, state.characters)')
    expect(applyPostprocess).toContain('if (payload.statusState && typeof payload.statusState === \'object\')')
    expect(applyPostprocess).toContain('state.statusState = normalizeStatusState(payload.statusState, state.statusRoster, state.characters, state.statusSchema)')
    expect(applyPostprocess).toContain('state.statusState = mergeStatusState(state.statusState, statusPatch.statusStatePatch, state.statusRoster, state.characters, state.statusSchema)')
  })

  it('keeps core identity and pose fields without forcing the full fallback status schema', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
    const initializer = fs.readFileSync(path.join(process.cwd(), 'prompts/initializer.md'), 'utf-8')

    expect(appJs).toContain("const requiredStatusSchema = ['性别', '身份', '外貌', '性格', '姿势']")
    expect(appJs).toContain("const fallbackStatusSchema = ['性别', '身份', '外貌', '性格', '姿势', '位置']")
    expect(appJs).toContain('const fields = parseStatusSchemaFields(value)')
    expect(appJs).toContain('const source = fields.length ? fields : fallback')
    expect(appJs).toContain('function statusFieldValue')
    expect(appJs).toContain('if (record[field] !== undefined && record[field] !== null) return String(record[field])')
    expect(appJs).toContain("return String(fallbackByField[field] || '')")
    expect(appJs).not.toContain('姿势: String(record.姿势')
    expect(appJs).not.toContain('手上物: String(record.手上物')
    expect(appJs).not.toContain('可触达区域: String(record.可触达区域')
    expect(appJs).toContain('for (const field of normalizeStatusSchema(schema))')
    expect(serverTs).toContain("const requiredStatusSchema = ['性别', '身份', '外貌', '性格', '姿势']")
    expect(serverTs).toContain("const fallbackStatusSchema = ['性别', '身份', '外貌', '性格', '姿势', '位置']")
    expect(serverTs).toContain('const fields = parseStatusSchemaFields(value)')
    expect(serverTs).toContain('const source = fields.length ? fields : fallback')
    expect(serverTs).toContain('function statusFieldValue')
    expect(serverTs).not.toContain('姿势: String(record.姿势')
    expect(serverTs).not.toContain('手上物: String(record.手上物')
    expect(serverTs).not.toContain('可触达区域: String(record.可触达区域')
    expect(serverTs).toContain('gender?: string')
    expect(serverTs).toContain('appearance?: string')
    expect(serverTs).toContain('personality?: string')
    expect(initializer).not.toContain('`cast`')
    expect(initializer).toContain('必须包含 `性别`、`身份`、`外貌`、`性格`、`姿势`')
    expect(initializer).toContain('发挥判断力')
    expect(initializer).toContain('不得原样输出占位词')
    expect(initializer).toContain('不要只写“玩家”')
    expect(initializer).not.toContain('id/name/gender')
    expect(initializer).not.toContain('location/health/trust')
  })

  it('keeps story characters in the status roster even when saved roster only has player', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const normalizeRoster = extractFunction(appJs, 'normalizeStatusRoster')

    expect(normalizeRoster).toContain('const characterNames = characters.map')
    expect(normalizeRoster).toContain("return [...new Set(['玩家', ...names, ...characterNames])]")
  })

  it('removes evaluator code instead of keeping it hidden', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(html).not.toContain('评估模块')
    expect(html).not.toContain('id="evaluationTargetSelect"')
    expect(html).not.toContain('id="refreshEvaluationButton"')
    expect(html).not.toContain('id="evaluateTurnButton"')
    expect(html).not.toContain('id="evaluationReport"')
    expect(html).not.toContain('id="evaluationInput"')
    expect(appJs).not.toContain('function evaluateLatestTurn')
    expect(appJs).not.toContain('function prepareEvaluationMaterialFromState')
    expect(appJs).not.toContain("fetch('/api/evaluation-material'")
    expect(appJs).not.toContain("fetch('/api/evaluation-latest'")
    expect(appJs).not.toContain('function buildEvaluationPayloadFromState')
    expect(appJs).not.toContain('function normalizeEvaluationTarget')
    expect(appJs).not.toContain("fetch('/api/evaluate-stream'")
    expect(appJs).not.toContain('function renderEvaluation')
    expect(serverTs).not.toContain("const evaluationMaterialDir = path.join(debugDir, 'evaluation-materials')")
    expect(serverTs).not.toContain('function writeEvaluationMaterialFile')
    expect(serverTs).not.toContain("url.pathname === '/api/evaluation-material'")
    expect(serverTs).not.toContain("url.pathname === '/api/evaluation-latest'")
    expect(serverTs).not.toContain("url.pathname === '/api/evaluate-stream'")
    expect(serverTs).not.toContain("renderPromptMessagePair('evaluator.md'")
    expect(serverTs).not.toContain("stage: 'evaluator'")
    expect(serverTs).not.toContain('debug/evaluations/latest.json')
    expect(serverTs).not.toContain('function writeEvaluationDebugFile')
  })

  it('keeps generation simple by removing next-turn prewarm caches', () => {
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(serverTs).not.toContain("url.pathname === '/api/director-prewarm'")
    expect(serverTs).not.toContain('director-cache.json')
    expect(serverTs).not.toContain('narrator-cache.json')
    expect(serverTs).not.toContain('postprocess-cache.json')
    expect(serverTs).not.toContain('PREWARM_FULL_PIPELINE')
    expect(serverTs).not.toContain('prewarmEpoch')
    expect(serverTs).not.toContain('function cancelAllPrewarmJobs')
    expect(serverTs).not.toContain("url.pathname === '/api/prewarm-cancel'")
    expect(serverTs).not.toContain('function startDirectorPrewarm')
    expect(serverTs).not.toContain('function startNarratorPrewarm')
    expect(serverTs).not.toContain('function startPostprocessPrewarm')
    expect(serverTs).toContain('function buildNarratorPromptPayload')
    expect(serverTs).toContain('function buildPostprocessPromptPayload')
    expect(serverTs).not.toContain('narratorPrewarmJobs')
    expect(serverTs).not.toContain('postprocessPrewarmJobs')
    expect(serverTs).not.toContain('等待命中的后台 Narrator 预热结果。')
    expect(serverTs).not.toContain('等待命中的后台 Postprocess 预热结果。')
    expect(serverTs).not.toContain('function awaitPrewarmJob')
    expect(appJs).not.toContain('function triggerDirectorPrewarm')
    expect(appJs).not.toContain('let prewarmController')
    expect(appJs).not.toContain('let prewarmEpoch')
    expect(appJs).not.toContain('function nextPrewarmEpoch')
    expect(appJs).not.toContain('function cancelClientPrewarm')
    expect(appJs).not.toContain("fetch('/api/prewarm-cancel'")
    expect(appJs).toContain('function normalizeStatusSchema')
    expect(appJs).toContain('function normalizeStatusRoster')
    expect(appJs).toContain('multiCharacterStatusMigration')
    expect(appJs).toContain('state.statusSchema = normalizeStatusSchema(payload.statusSchema)')
    expect(appJs).toContain('state.statusRoster = normalizeStatusRoster(payload.statusRoster, state.characters)')
    expect(appJs).toContain('state.statusState = normalizeStatusState(payload.statusState, state.statusRoster, state.characters, state.statusSchema)')
    expect(appJs).toContain('function buildRecentTurnsForRequest')
    expect(appJs).toContain('return withOpening.slice(-11)')
    expect(appJs).not.toContain('Next Turn Prewarm')
    expect(appJs).not.toContain("fetch('/api/director-prewarm'")
    expect(appJs).toContain('Narrator')
    expect(appJs).toContain('Postprocess')
  })

  it('keeps current plot as the latest turn instead of accumulating history', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const postprocessPrompt = fs.readFileSync(path.join(process.cwd(), 'prompts/postprocess.md'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(appJs).not.toContain('const currentPlot = state.outline || state.currentSituation')
    expect(appJs).not.toContain("renderTrackerSection('当前剧情'")
    expect(appJs).toContain('const labeledTurnSummary = labelTurnSummary(turnSummary, completedAssistantTurnCount())')
    expect(appJs).toContain('state.outline = turnSummary')
    expect(appJs).toContain('return `第${Math.max(1, index)}轮：${text}`')
    expect(appJs).toContain('function openingTurnHistory')
    expect(appJs).toContain('const openingHistory = openingTurnHistory(openingText)')
    expect(appJs).toContain('const hasNoInteraction = messages.length === 0')
    expect(appJs).toContain('const chapterSummary = hasNoInteraction && isOpeningHistorySummary(existingChapterSummary, openingHistory) ? \'\' : existingChapterSummary')
    expect(appJs).toContain('const globalContext = hasNoInteraction && isOpeningHistorySummary(existingGlobalContext, openingHistoryLine) ? \'\' : existingGlobalContext')
    expect(appJs).toContain('function isOpeningHistorySummary')
    expect(appJs).toContain("renderTrackerSection('历史总结', formatHistoricalSummaryForTracker(summary)")
    expect(appJs).toContain('function formatHistoricalSummaryForTracker')
    expect(appJs).toContain('return `- 第${index + 1}轮：${line}`')
    expect(appJs).toContain("const openingSummary = String(story.openingText || '').trim()")
    expect(appJs).not.toContain('story.chapterSummary = labeledOpeningSummary')
    expect(appJs).toContain('story.chapterSummary = \'\'')
    expect(appJs).toContain('story.globalContext = \'\'')
    expect(appJs).not.toContain('function summarizeOpeningTextForHistory')
    expect(appJs).not.toContain('story.globalContext = rebuildStoryGlobalContext')
    expect(appJs).not.toContain('state.globalContext = rebuildStoryGlobalContext')
    expect(appJs).toContain('chapterSummary,')
    expect(appJs).toContain('globalContext,')
    expect(appJs).toContain('return text && !isStoryMetadataLine(text)')
    expect(appJs).toContain('故事导演风格|故事叙事风格')
    expect(postprocessPrompt).toContain('"turnSummary"')
    expect(postprocessPrompt).toContain('10-35 字')
    expect(postprocessPrompt).toContain('只记【最终正文】中本轮一个最关键已发生事实')
    expect(serverTs).toContain('normalizeTurnSummary(postprocess.json.turnSummary, finalText)')
    expect(serverTs).not.toContain('deriveTurnSummaryFromDirectorPlan')
    expect(appJs).not.toContain('payload.outlinePatch')
    expect(appJs).not.toContain('payload.globalContextPatch')
    expect(appJs).not.toContain('appendBulletText(state.outline, payload.outlinePatch')
  })

  it('keeps repetition feedback as a one-turn memory', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('feedbackMemory: []')
    expect(appJs).toContain('function mergeFeedbackMemory')
    expect(appJs).toContain('ttl: 1')
    expect(appJs).toContain('item.ttl - 1')
    expect(appJs).toContain('feedbackText: renderFeedbackMemory()')
    expect(appJs).not.toContain("['directorPositive', payload.directorPositiveFeedback]")
    expect(appJs).not.toContain("['narratorPositive', payload.narratorPositiveFeedback]")
    expect(appJs).not.toContain("['planExecution', payload.planExecutionFeedback]")
    expect(appJs).toContain("['narrativeRepetition', payload.存在重复 || payload.narrativeRepetitionFeedback]")
    expect(appJs).not.toContain("['narrativePacing', payload.节奏不足 || payload.narrativePacingFeedback]")
    expect(appJs).not.toContain("['directorPhysical', payload.导演物理违背 || payload.directorPhysicalFeedback]")
    expect(appJs).not.toContain("directorPositive: '导演正反馈'")
    expect(appJs).not.toContain("narratorPositive: '叙事正反馈'")
    expect(appJs).not.toContain("planExecution: '执行'")
    expect(appJs).toContain("narrativeRepetition: '存在重复'")
    expect(appJs).not.toContain("narrativePacing: '节奏不足'")
    expect(appJs).not.toContain("directorPhysical: '导演物理违背'")
    expect(appJs).toContain('state.feedbackMemory = mergeFeedbackMemory(state.feedbackMemory, payload)')
    expect(appJs).not.toContain('state.feedbackMemory = renderFeedbackMemory(state.feedbackMemory)')
    expect(appJs).toContain("renderTrackerSection('上轮反重复提醒'")
    expect(appJs).not.toContain('logicGuidance')
    expect(appJs).not.toContain("renderTrackerSection('逻辑提醒'")
    expect(appJs).not.toContain('characterUpdates: state.characterUpdates')
  })

  it('does not keep a separate physical environment state lane', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).not.toContain('function renderPhysicalEnvironment')
    expect(appJs).not.toContain('currentPhysicalEnvironment')
    expect(appJs).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(appJs).not.toContain("renderTrackerSection('当前物理环境'")
    expect(appJs).not.toContain('plotState')
    expect(appJs).not.toContain('function defaultPlotState')
    expect(appJs).not.toContain('function normalizePlotState')
    expect(appJs).not.toContain('function renderPlotState')
    expect(appJs).not.toContain('jumpToNextPhysicalScene')
  })

  it('shows the plot goal instead of current and next plot', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain("renderTrackerSection('当前剧情目标'")
    expect(appJs).toContain("story.plotGoal = String(init.plotGoal || '')")
    expect(appJs).toContain('plotGoal: state.plotGoal')
    expect(appJs).toContain("if (typeof payload.plotGoal === 'string') state.plotGoal = payload.plotGoal.trim()")
    expect(appJs).not.toContain("renderTrackerSection('Current Plot'")
    expect(appJs).not.toContain("renderTrackerSection('Next Plot'")
    expect(appJs).not.toContain("missing.push('longRangeOutline')")
    expect(appJs).not.toContain('formatDirectorLongRange')
    expect(appJs).not.toContain('longRangeUpdate')
    expect(appJs).not.toContain('longRangeOutline')
  })

  it('does not keep a separate foreshadow queue', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')
    const serverTs = fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')

    expect(appJs).not.toContain('foreshadowRecords')
    expect(appJs).not.toContain('function mergeForeshadowRecords')
    expect(appJs).not.toContain('function isSimilarForeshadow')
    expect(serverTs).not.toContain('renderForeshadowContext')
    expect(serverTs).not.toContain('foreshadowRecords')
    expect(serverTs).not.toContain('foreshadows:')
  })

  it('renders status panel as raw JSON', () => {
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(appJs).toContain('<pre class="status-json">${escapeHtml(JSON.stringify(state.statusState || {}, null, 2))}</pre>')
    expect(appJs).not.toContain('function renderStatusPanelBody')
    expect(appJs).not.toContain('function tryParseJsonStatusPanel')
    expect(appJs).not.toContain('function renderStatusField')
  })

  it('exposes official, Infron, Fireworks, Google AI Studio, and Cerebras models', () => {
    const html = readIndexHtml()
    const appJs = fs.readFileSync(path.join(process.cwd(), 'web/app.js'), 'utf-8')

    expect(html).toContain('id="providerSelect"')
    expect(html).toContain('供应商')
    expect(html).toContain('value="fireworks"')
    expect(html).toContain('value="infron"')
    expect(html).toContain('value="deepseek"')
    expect(appJs).toContain('const modelCatalog = [')
    expect(appJs).toContain('provider: \'fireworks\'')
    expect(appJs).toContain('provider: \'infron\'')
    expect(appJs).toContain('function modelsForProvider')
    expect(appJs).toContain('function defaultModelForProvider')
    expect(appJs).toContain('if (normalizeProvider(provider) === providerForModel(defaultModel)) return defaultModel')
    expect(appJs).toContain('els.modelSelect.innerHTML = modelsForProvider(provider).map')
    expect(html).not.toContain('gemini-3.1-flash-lite-preview')
    expect(html).not.toContain('qwen/qwen3.5-flash-02-23')
    expect(html).not.toContain('gemma-4-uncensored')
    expect(html).not.toContain('value="accounts/fireworks/models/deepseek-v4-pro"')
    expect(appJs).toContain('fireworksApiKeyStorageKey')
    expect(appJs).toContain('infronApiKeyStorageKey')
    expect(appJs).toContain('cerebrasApiKeyStorageKey')
    expect(appJs).toContain('googleAiStudioApiKeyStorageKey')
    expect(appJs).toContain('fireworksDeepSeekV4ProPriorityModel')
    expect(appJs).toContain('fireworksKimiK2P5Model')
    expect(appJs).toContain('fireworksQwen3235BA22BModel')
    expect(appJs).toContain('fireworksQwen36PlusModel')
    expect(appJs).not.toContain('fireworksGemma431BItModel')
    expect(appJs).not.toContain('fireworksDeepSeekV3P2Model')
    expect(appJs).not.toContain('deepseek-v3p2')
    expect(appJs).toContain('infronDeepSeekV4ProModel')
    expect(appJs).toContain('infronDeepSeekV4FlashModel')
    expect(appJs).toContain("const infronDeepSeekV4ProModel = 'deepseek/deepseek-v4-pro'")
    expect(appJs).toContain("const infronDeepSeekV4FlashModel = 'deepseek/deepseek-v4-flash'")
    expect(appJs).toContain('infronGemini31FlashLiteModel')
    expect(appJs).toContain('infronGemini25FlashModel')
    expect(appJs).toContain('infronGemini3FlashPreviewModel')
    expect(appJs).toContain('infronKimiK25Model')
    expect(appJs).toContain('infronQwen35EaricaModel')
    expect(appJs).toContain('infronQwen36FlashModel')
    expect(appJs).toContain('infronQwen36PlusModel')
    expect(appJs).toContain('infronXiaomiMimo25Model')
    expect(appJs).toContain('infronGlm47FlashxModel')
    expect(appJs).toContain('infronGlm51Model')
    expect(appJs).toContain('infronGrok43Model')
    expect(appJs).toContain('googleAiStudioGemini31FlashLiteModel')
    expect(appJs).toContain('cerebrasQwenModel')
    expect(appJs).not.toContain("const fireworksDeepSeekV4ProModel")
    expect(appJs).toContain('officialDeepSeekV4FlashModel')
    expect(appJs).toContain('DeepSeek V4 Flash | official | DeepSeek')
    expect(appJs).toContain('const defaultModel = officialDeepSeekV4FlashModel')
    expect(appJs).toContain('pipelineModels: raw?.pipelineModels')
    expect(appJs).not.toContain('function savePromptProfile')
    expect(appJs).not.toContain("fetch('/api/prompt-profile'")
    expect(appJs).not.toContain('let pendingPromptProfileSelection = null')
    expect(appJs).not.toContain('function selectedPromptProfileForManagement')
    expect(appJs).toContain('initializer: defaultModel')
    expect(appJs).toContain('narrator: defaultModel')
    expect(appJs).toContain('function getPipelineApiKey')
    expect(appJs).toContain('function getPipelineApiKeys')
    expect(appJs).toContain('apiKeys: getPipelineApiKeys()')
    expect(appJs).toContain('return getLocalApiKey(currentProvider())')
    expect(appJs).toContain('let pendingModelSelection = null')
    expect(appJs).toContain('const preferredModelStorageKey')
    expect(appJs).toContain('const preferredModelVersionStorageKey')
    expect(appJs).toContain("const defaultModelVersion = 'official-deepseek-v4-flash'")
    expect(appJs).toContain('function normalizePersistedModel')
    expect(appJs).toContain('version !== defaultModelVersion && model === infronGrok43Model')
    expect(appJs).toContain('function getActiveModel')
    expect(appJs).toContain('function setPreferredModel')
    expect(appJs).toContain('preferredModel: story.model')
    expect(appJs).toContain('function applyModelSelection')
    expect(appJs).toContain('setPreferredModel(model)')
    expect(appJs).toContain('pendingModelSelection = null')
    expect(appJs).toContain('pendingModelSelection = normalizeModel(event.target.value)')
    expect(appJs).toContain('pendingModelSelection = defaultModelForProvider(event.target.value)')
    expect(appJs).toContain('pendingModelSelection = defaultModelForProvider(providerForModel(button.dataset.providerModel))')
    expect(appJs).toContain('const requestModel = normalizeModel(effectiveRequestPayload.model || getActiveModel())')
    expect(appJs).toContain('setPreferredModel(requestModel)')
    expect(appJs).toContain('setPreferredModel(payload.model || requestModel)')
    expect(appJs).toContain('selectedModelForManagement()')
    expect(appJs).toContain('els.applyModelSelectionButton.disabled = !hasPendingChange')
    expect(appJs).toContain('function pipelineModelsForSelection')
    expect(appJs).toContain('function renderPipelineModelGrid')
    expect(appJs).toContain('els.pipelineModelGrid.innerHTML')
    expect(appJs).not.toContain('长期导演')
    expect(appJs).toContain('后处理')
    expect(appJs).not.toContain("if (provider !== 'deepseek')")
    expect(appJs).toContain('director: normalized')
    expect(appJs).toContain('postprocess: normalized')
    expect(appJs).toContain('当前模型')
    expect(appJs).toContain('sort=throughput')
    expect(html).toContain('id="modelManagementPage"')
    expect(html).toContain('id="modelManagementButton"')
    expect(html).toContain('id="pipelineModelGrid"')
    expect(html).toContain('id="applyModelSelectionButton"')
    expect(html).toContain('确定')
    expect(html).toContain('id="modelTestResults"')
    expect(html).toContain('id="providerSpeedTestButton"')
    expect(html).not.toContain('id="promptProfileSelect"')
    expect(html).not.toContain('Prompt 版本')
    expect(html).toContain('id="buildInterceptionPromptButton"')
    expect(html).toContain('id="interceptionPromptFile"')
    expect(html).toContain('id="interceptionInstructionFiles"')
    expect(html).toContain('id="runInterceptionTestButton"')
    expect(html).toContain('id="interceptionSystemInput"')
    expect(html).toContain('id="interceptionResultOutput"')
    expect(appJs).toContain('function renderModelTestResult')
    expect(appJs).toContain("fetch('/api/provider-test'")
    expect(appJs).toContain("fetch('/api/provider-speed-test'")
    expect(appJs).toContain('function testCurrentProviderSpeed')
    expect(appJs).toContain("fetch('/api/content-interception/prompt'")
    expect(appJs).toContain("fetch('/api/content-interception/test'")
    expect(appJs).toContain('function buildCurrentInterceptionPrompt')
    expect(appJs).toContain('function loadInterceptionPromptFile')
    expect(appJs).toContain('function runContentInterceptionTest')
    expect(appJs).toContain('TTFT')
    expect(appJs).toContain('TPS')
    expect(appJs).toContain('apiKey: getPipelineApiKey()')
    expect(appJs).toContain('renderPipelineModelGrid(model, pipelineModels)')
    expect(appJs).toContain('pipeline-model-card')
    expect(appJs).toContain('Fireworks')
    expect(appJs).toContain('Cerebras')
    expect(appJs).toContain('Google AI Studio')
    expect(appJs).toContain('api.fireworks.ai/inference/v1')
    expect(appJs).toContain('llm.onerouter.pro/v1')
    expect(appJs).toContain('api.cerebras.ai/v1')
    expect(appJs).toContain('generativelanguage.googleapis.com/v1beta/openai')
    expect(appJs).not.toContain('googleApiKeyStorageKey')
    expect(appJs).not.toContain('openRouterApiKeyStorageKey')
    expect(appJs).not.toContain('veniceApiKeyStorageKey')
  })
})
