import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readPrompt(relativePath: string): string {
  return fs.readFileSync(path.join(process.cwd(), relativePath), 'utf-8')
}

describe('prompt contracts', () => {
  it('keeps hard rules minimal and free of maintenance notes', () => {
    const prompt = readPrompt('prompts/system-hard-rules/hard-rules.md')

    expect(prompt).toContain('玩家输入优先')
    expect(prompt).toContain('只输出合法 JSON')
    expect(prompt).toContain('draftText')
    expect(prompt).toContain('finalText')
    expect(prompt).not.toContain('用途：')
    expect(prompt).not.toContain('什么时候用')
    expect(prompt).not.toContain('怎么用')
    expect(prompt).not.toContain('---')
  })

  it('keeps director output compact and free of report-only fields', () => {
    const prompt = readPrompt('prompts/director/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('输出必须压缩')
    expect(prompt).toContain('主动制造剧情')
    expect(prompt).toContain('轻/中度扰动')
    expect(prompt).toContain('NPC 主动意图')
    expect(prompt).toContain('当前伏笔')
    expect(prompt).toContain('payoff')
    expect(prompt).toContain('drop')
    expect(prompt).toContain('当前长期剧情')
    expect(prompt).toContain('currentSceneForbidden')
    expect(prompt).toContain('不得新增独立约束字段')
    expect(prompt).toContain('sceneDecision')
    expect(prompt).toContain('只读取当前长期剧情')
    expect(prompt).toContain('不得新建、微调、替换当前长期剧情')
    expect(prompt).not.toContain('"mode": "keep | create | adjust | replace"')
    expect(prompt).not.toContain('"longRangeUpdate"')
    expect(prompt).not.toContain('自行生成第一个当前长期剧情')
    expect(prompt).not.toContain('自行修订当前长期剧情')
    expect(prompt).toContain('玩家意图不是剧情最高目标')
    expect(prompt).toContain('世界合理运转')
    expect(prompt).toContain('上帝模式导演要求')
    expect(prompt).toContain('避免剧情滑向')
    expect(prompt).toContain('整个 JSON 尽量控制在 400-800 tokens')
    expect(prompt).toContain('不输出 `reason`')
    expect(prompt).toContain('不复述固定配置和用户注入配置')
    expect(prompt).toContain('不输出纯结构索引和内部分类')
    expect(prompt).not.toContain('"reason"')
    expect(prompt).not.toContain('"editorChecklist"')
    expect(prompt).not.toContain('"targetTextRange"')
    expect(prompt).not.toContain('"beatWordPlan"')
    expect(prompt).not.toContain('"turnIndex"')
    expect(prompt).not.toContain('"povPolicy"')
    expect(prompt).not.toContain('"pov"')
    expect(prompt).not.toContain('"targetWords"')
    expect(prompt).not.toContain('"kind"')
    expect(prompt).not.toContain('"beatId"')
    expect(prompt).not.toContain('"descriptionPlans"')
    expect(prompt).not.toContain('"spatialBlocking"')
    expect(prompt).not.toContain('"stateUpdates"')
    expect(prompt).not.toContain('"neededPostprocess"')
    expect(prompt).not.toContain('"postprocessPlan"')
    expect(prompt).not.toContain('"requirementReinforcement"')
    expect(prompt).not.toContain('"preflight"')
    expect(prompt).not.toContain('"pacing"')
    expect(prompt).not.toContain('"exitWindow"')
    expect(prompt).toContain('"beats"')
    expect(prompt).toContain('"brief"')
    expect(serverSource).toContain('function compactDirectorPlan')
    expect(serverSource).not.toContain('function runStoryCuratorCall')
    expect(serverSource).not.toContain("stage: 'story-curator'")
    expect(serverSource).not.toContain('shouldRequestStoryCurator')
    expect(serverSource).toContain('function compactDescriptionFocus')
    expect(serverSource).toContain('directorGuidance?: string')
    expect(serverSource).toContain("block('上帝模式导演要求'")
    expect(serverSource).toContain('JSON.stringify(options.directorPlan)')
    expect(serverSource).toContain('sceneDecision: compactText')
    expect(serverSource).not.toContain('sceneLimits: compactStringArray')
    expect(serverSource).toContain('spatialState: string')
    expect(serverSource).toContain('block(\'叙事空间输入\', options.context.spatialState)')
    expect(serverSource).not.toContain('targetTextRange: compactText')
    expect(serverSource).not.toContain('beatWordPlan: requirement.beatWordPlan')
    expect(serverSource).not.toContain('targetWords:')
    expect(serverSource).not.toContain('kind:')
    expect(serverSource).not.toContain('spatialBlocking:')
    expect(serverSource).not.toContain('stateUpdates:')
    expect(serverSource).not.toContain('postprocessPlan:')
    expect(prompt).not.toContain('sceneLimits')
  })

  it('internalizes modular plot construction and description-chain guidance in director', () => {
    const prompt = readPrompt('prompts/director/prompt.md')

    expect(prompt).toContain('高效的剧情创作方法')
    expect(prompt).toContain('三个剧情事件模块和一个结尾模块')
    expect(prompt).toContain('环境模块')
    expect(prompt).toContain('推进模块')
    expect(prompt).toContain('插入模块')
    expect(prompt).toContain('新输出的三个剧情模块的种类和顺序不得与上次雷同')
    expect(prompt).toContain('描写发展链指导')
    expect(prompt).toContain('集中｜')
    expect(prompt).toContain('推进｜')
    expect(prompt).toContain('思想锚点')
    expect(prompt).toContain('主题内化')
    expect(prompt).toContain('冲突动力学')
    expect(prompt).toContain('五官')
    expect(prompt).toContain('新鲜特写')
    expect(prompt).toContain('动作神态')
    expect(prompt).toContain('不得把模块标签、过渡标签或 <po> 示例写进正文')
  })

  it('keeps director pacing balanced between trivial drag and major-event fast-forward', () => {
    const prompt = readPrompt('prompts/director/prompt.md')

    expect(prompt).toContain('剧情推进速度不得过慢')
    expect(prompt).toContain('小事可几笔带过')
    expect(prompt).toContain('不得出现一次输出内直接将当前大事件推进至末尾')
    expect(prompt).toContain('整合小事件')
    expect(prompt).toContain('为用户保留互动空间')
    expect(prompt).toContain('增强用户的互动感')
  })

  it('keeps director enforcing character independence and player authority boundaries', () => {
    const prompt = readPrompt('prompts/director/prompt.md')

    expect(prompt).toContain('没有一个角色是天然主角')
    expect(prompt).toContain('所有角色都具有思维上的独立性')
    expect(prompt).toContain('不会无条件依附于玩家角色')
    expect(prompt).toContain('好感度不会无缘无故因小事上涨或下降')
    expect(prompt).toContain('符合或不符合 NPC 喜好')
    expect(prompt).toContain('操控非玩家角色')
    expect(prompt).toContain('直接判定剧情某件事情的成功或失败')
    expect(prompt).toContain('作弊性道具和技能')
    expect(prompt).toContain('无视并不执行')
  })

  it('keeps long arc ownership in postprocess plus high-level director', () => {
    const initializer = readPrompt('prompts/initializer/prompt.md')
    const director = readPrompt('prompts/director/prompt.md')
    const postprocess = readPrompt('prompts/postprocess/prompt.md')
    const longRangeDirector = readPrompt('prompts/long-range-director/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(initializer).toContain('初始化阶段不生成当前长期剧情')
    expect(initializer).not.toContain('longRangeOutline')
    expect(initializer).not.toContain('第一个当前长期剧情')
    expect(director).toContain('只读取当前长期剧情')
    expect(director).toContain('不得新建、微调、替换当前长期剧情')
    expect(director).not.toContain('"completion"')
    expect(postprocess).toContain('"longRangeStatus"')
    expect(postprocess).toContain('keep|completed|missing')
    expect(postprocess).toContain('只在 missing 或 completed 时调用高级 Director')
    expect(postprocess).not.toContain('drifted')
    expect(postprocess).toContain('只判断当前长期剧情是否需要高级 Director 介入')
    expect(longRangeDirector).toContain('高级 Director')
    expect(longRangeDirector).toContain('只在 Postprocess 判断需要时调用')
    expect(longRangeDirector).toContain('missing')
    expect(longRangeDirector).toContain('completed')
    expect(longRangeDirector).not.toContain('drifted')
    expect(longRangeDirector).toContain('"longRangeOutline"')
    expect(serverSource).toContain("block('当前长期剧情'")
    expect(serverSource).toContain("readPrompt('long-range-director/prompt.md')")
    expect(serverSource).toContain('function shouldRunLongRangeDirector')
    expect(serverSource).toContain("return status === 'missing' || status === 'completed'")
    expect(serverSource).toContain('postprocess.json.longRangeStatus')
    expect(serverSource).not.toContain('formatLongRangePlanning(directorPlan.longRangeUpdate')
    expect(readPrompt('src/promptPipeline.ts')).not.toContain('longRangeUpdate')
    expect(serverSource).not.toContain("readPrompt('story-curator/prompt.md')")
  })

  it('uses single-text narrator output without paragraph patch fields', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')
    const pipelineSource = readPrompt('src/promptPipeline.ts')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('"draftText"')
    expect(prompt).toContain('字数是软目标')
    expect(prompt).toContain('宁可略超字数')
    expect(prompt).toContain('完整收束')
    expect(prompt).not.toContain('默认正文 600-900 字')
    expect(prompt).not.toContain('硬上限 900 字')
    expect(prompt).toContain('currentSceneForbidden')
    expect(prompt).not.toContain('sceneLimits')
    expect(prompt).not.toContain('draftParagraphs')
    expect(pipelineSource).not.toContain('draftParagraphs')
    expect(serverSource).toContain('narratorMaxTokens')
    expect(serverSource).toContain('const narratorMaxTokens = 8192')
    expect(serverSource).toContain('maxTokens: narratorMaxTokens')
    expect(serverSource).toContain('version: 3')
  })

  it('keeps narrator free of explicit self-check output', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')
    const pipelineSource = readPrompt('src/promptPipeline.ts')

    expect(prompt).toContain('OOC')
    expect(prompt).toContain('物理姿势')
    expect(prompt).toContain('玩家主导')
    expect(prompt).not.toContain('输出前静默自修')
    expect(prompt).not.toContain('必须自修一遍')
    expect(prompt).not.toContain('审查意见')
    expect(prompt).not.toContain('draftChecks')
    expect(pipelineSource).not.toContain('draftChecks')
  })

  it('keeps character perception limited and internalizes broad novel craft in narrator', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')

    expect(prompt).toContain('所有角色都是身处于此作品世界的')
    expect(prompt).toContain('第一人称限知视角')
    expect(prompt).toContain('一个或多个感知过程')
    expect(prompt).toContain('看、听、闻、尝、触、感')
    expect(prompt).toContain('思考推理')
    expect(prompt).toContain('不得让角色无过渡无准备直接了解角色设定和世界观')
    expect(prompt).toContain('全面小说创作指导')
    expect(prompt).toContain('思想锚点')
    expect(prompt).toContain('主题内化')
    expect(prompt).toContain('冲突动力学')
    expect(prompt).toContain('心路历程')
    expect(prompt).toContain('距离控制')
    expect(prompt).toContain('感官共鸣')
    expect(prompt).toContain('新鲜特写')
    expect(prompt).toContain('点滴渗透')
    expect(prompt).toContain('文质相符')
    expect(prompt).toContain('动作神态')
  })

  it('uses recent detailed text as anti-repetition context for narrator', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')
    const appJs = readPrompt('web/app.js')

    expect(prompt).toContain('第一优先：【抗重复需求】')
    expect(prompt).toContain('【最近正文】')
    expect(prompt).toContain('反重复参照')
    expect(prompt).toContain('滥用反复描写手法')
    expect(prompt).toContain('前否后肯句式')
    expect(prompt).toContain('与上文句式和内容雷同')
    expect(prompt).toContain('上一轮已经写完的事实')
    expect(prompt).toContain('只能一句带过')
    expect(serverSource).toContain("block('最近正文', options.context.recentTurns)")
    expect(serverSource).toContain('recentTurns: renderConversation(input.recentTurns)')
    expect(appJs).toContain('recentTurns: buildRecentTurnsForRequest(playerInput)')
  })

  it('internalizes narrator defect guardrails and body-text banned library', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')

    expect(prompt).toContain('第一优先：【叙述缺陷规避】')
    expect(prompt).toContain('角色适度情感化')
    expect(prompt).toContain('拒绝滥用“自然”')
    expect(prompt).toContain('文风情感化')
    expect(prompt).toContain('角色都是独立的')
    expect(prompt).toContain('指导式')
    expect(prompt).toContain('刻薄式')
    expect(prompt).toContain('恶意式')
    expect(prompt).toContain('油腻式')
    expect(prompt).toContain('注重作品逻辑')
    expect(prompt).toContain('描写段句式段格式自由化')
    expect(prompt).toContain('角色对性反应正常化')
    expect(prompt).toContain('刻画角色时去刻板印象')
    expect(prompt).toContain('第一优先：【禁库限制】')
    expect(prompt).toContain('不是……而是')
    expect(prompt).toContain('段落开头使用她/他')
    expect(prompt).toContain('禁库内容处理痕迹')
    expect(prompt).toContain('只约束 `draftText` 正文')
  })

  it('keeps narrator length as a soft target instead of a hard cutoff', () => {
    const prompt = readPrompt('prompts/narrator/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('字数是软目标')
    expect(prompt).toContain('不得为了硬控字数截断句子')
    expect(prompt).toContain('如果正文明显超过目标')
    expect(prompt).not.toContain('硬上限')
    expect(serverSource).not.toContain('loadUserConfigDefault')
    expect(serverSource).not.toContain("path.join(userConfigDir, 'default-config.json')")
  })

  it('loads user config only from the new style directory and enforces one enabled style per layer', () => {
    const serverSource = readPrompt('scripts/web-server.ts')
    const directorTemplate = readPrompt('prompts/user-config-templates/导演风格/导演风格模板.md')
    const narratorTemplate = readPrompt('prompts/user-config-templates/叙事风格/叙事风格模板.md')

    expect(serverSource).toContain("type UserModuleStage = 'director' | 'narrator'")
    expect(serverSource).toContain("const userConfigDir = path.join(promptDir, 'user-config-templates')")
    expect(serverSource).not.toContain('userConfigTemplateDir')
    expect(serverSource).not.toContain("path.join(promptDir, 'user-config')")
    expect(serverSource).not.toContain('configRoots')
    expect(serverSource).toContain('function enforceSingleEnabledStylePerLayer')
    expect(serverSource).toContain('styleExclusiveGroup(module.layer)')
    expect(serverSource).toContain('function renderModulesForStage')
    expect(serverSource).toContain("renderModulesForStage(modules, 'director')")
    expect(serverSource).toContain("renderModulesForStage(options.modules, 'narrator')")
    expect(serverSource).not.toContain("renderModulesForStage(input.userModules, 'postprocess')")
    expect(serverSource).toContain("block('导演风格配置'")
    expect(serverSource).not.toContain("renderModulesForStage(modules, 'editor')")
    expect(serverSource).not.toContain("block('用户注入模块', renderModulesForStage(input.userModules")
    expect(directorTemplate).toContain('layer: "director"')
    expect(directorTemplate).toContain('group: "导演风格"')
    expect(narratorTemplate).toContain('layer: "narrator"')
    expect(narratorTemplate).toContain('group: "叙事风格"')
  })

  it('keeps postprocess read-only for visible text', () => {
    const prompt = readPrompt('prompts/postprocess/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('不得修改正文')
    expect(prompt).toContain('qualityFeedback')
    expect(prompt).toContain('写作负反馈')
    expect(prompt).toContain('允许本轮正文有轻微偏差')
    expect(prompt).toContain('只输出本轮事实一句')
    expect(prompt).toContain('"playerOptions": ["')
    expect(prompt).toContain('三个选项必须是三种不同倾向')
    expect(prompt).toContain('longRangeStatus')
    expect(prompt).toContain('只判断当前长期剧情是否需要高级 Director 介入')
    expect(prompt).toContain('推进/靠近')
    expect(prompt).toContain('试探/询问')
    expect(prompt).toContain('保留/转移')
    expect(prompt).toContain('禁止三个选项只是同一行动换说法')
    expect(prompt).toContain('不是单纯菜单')
    expect(prompt).toContain('剧情推进动力')
    expect(prompt).toContain('转折点')
    expect(prompt).toContain('必须基于【最近正文】、【长期剧情总结】、【当前长期剧情】、【当前伏笔】、【导演摘要】和【最终正文】')
    expect(serverSource).toContain("block('长期剧情总结', globalContext)")
    expect(serverSource).toContain("block('最近正文', context.recentTurns)")
    expect(serverSource).toContain("block('当前伏笔', renderForeshadowContext(input.foreshadowRecords, turnIndex))")
    expect(prompt).not.toContain('globalContextPatch')
    expect(prompt).not.toContain('outlinePatch')
    expect(prompt).not.toContain('foreshadowRecords')
    expect(prompt).not.toContain('logicGuidance')
    expect(prompt).not.toContain('逻辑提醒')
    expect(prompt).toContain('伏笔由 Director 决定')
    expect(prompt).not.toContain('characterUpdates')
    expect(prompt).not.toContain('"patches"')
    expect(prompt).not.toContain('"reviewFindings"')
    expect(prompt).not.toContain('ReviewerPostprocess')
    expect(serverSource).toContain('function extractDirectorForeshadowRecords')
    expect(serverSource).toContain('foreshadowRecords: extractDirectorForeshadowRecords(directorPlan)')
    expect(serverSource).not.toContain('foreshadowRecords: postprocess.json.foreshadowRecords')
    expect(serverSource).not.toContain('globalContextPatch: postprocess.json.globalContextPatch')
    expect(serverSource).not.toContain('outlinePatch: postprocess.json.outlinePatch')
  })

  it('feeds long-term quality feedback into director and narrator without making director verbose', () => {
    const director = readPrompt('prompts/director/prompt.md')
    const narrator = readPrompt('prompts/narrator/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).toContain('长期写作负反馈')
    expect(director).toContain('只转化为本轮规划约束')
    expect(narrator).toContain('长期写作负反馈')
    expect(narrator).toContain('不要输出反馈内容')
    expect(serverSource).toContain('qualityFeedback?: string')
    expect(serverSource).toContain("block('长期写作负反馈', String(input.qualityFeedback || '').trim(), '（无）')")
    expect(serverSource).toContain("block('长期写作负反馈', options.qualityFeedback, '（无）')")
    expect(serverSource).toContain("qualityFeedback: postprocess.json.qualityFeedback || ''")
    expect(serverSource).not.toContain('logicGuidance: postprocess.json.logicGuidance')
    expect(serverSource).not.toContain('characterUpdates: postprocess.json.characterUpdates')
  })

  it('persists sceneState as a four-field scene clock across the pipeline', () => {
    const director = readPrompt('prompts/director/prompt.md')
    const narrator = readPrompt('prompts/narrator/prompt.md')
    const postprocess = readPrompt('prompts/postprocess/prompt.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).toContain('当前环境状态')
    expect(director).toContain('currentScene')
    expect(director).toContain('nextScene')
    expect(director).toContain('transitionRule')
    expect(director).toContain('currentSceneForbidden')
    expect(director).toContain('若停留当前场景，必须给出阻滞原因')
    expect(director).toContain('Director 只判断本轮是否推进，不直接写回 sceneState')
    expect(director).toContain('sceneDecision')
    expect(narrator).toContain('当前环境状态')
    expect(narrator).toContain('currentSceneForbidden')
    expect(narrator).toContain('不得写出当前场景禁止的事件或动作')
    expect(postprocess).toContain('"sceneState"')
    expect(postprocess).toContain('"currentScene"')
    expect(postprocess).toContain('"nextScene"')
    expect(postprocess).toContain('"transitionRule"')
    expect(postprocess).toContain('"currentSceneForbidden"')
    expect(postprocess).toContain('不再输出一句普通环境描述')
    expect(postprocess).toContain('根据【最终正文】固化最新场景状态')
    expect(serverSource).toContain('interface SceneStateFields')
    expect(serverSource).toContain('type SceneStateInput')
    expect(serverSource).toContain('function normalizeSceneState')
    expect(serverSource).toContain('function renderSceneState')
    expect(serverSource).toContain("block('当前环境状态', renderSceneState")
    expect(serverSource).toContain('sceneState: normalizeSceneState(postprocess.json.sceneState, input.sceneState)')
    expect(serverSource).not.toContain('allowedTransitions')
    expect(serverSource).not.toContain('phaseTransition')
  })
})
