import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readPrompt(relativePath: string): string {
  return fs.readFileSync(path.join(process.cwd(), relativePath), 'utf-8')
}

describe('prompt contracts', () => {
  it('keeps compact hard rules as an explicit input block in every agent prompt', () => {
    const serverSource = readPrompt('scripts/web-server.ts')
    const hardRule = readPrompt('prompts/hard-rule.md')
    const agentPrompts = [
      'prompts/initializer.md',
      'prompts/initializer-revision.md',
      'prompts/director.md',
      'prompts/narrator.md',
      'prompts/summary.md',
      'prompts/summary-l2.md',
      'prompts/feedback.md',
      'prompts/recall-qa.md',
    ].map(readPrompt)

    expect(fs.existsSync(path.join(process.cwd(), 'prompts/system-hard-rules'))).toBe(false)
    expect(hardRule.trim()).toBeTruthy()
    for (const prompt of agentPrompts) {
      expect(prompt).not.toContain('# System Message')
      expect(prompt).not.toContain('# User Message')
      expect(prompt).toContain('## Hard Rule')
      expect(prompt).toContain('{{hardRule}}')
      expect(prompt.trimStart()).toContain('## Hard Rule\n{{hardRule}}')
    }
    expect(fs.existsSync(path.join(process.cwd(), 'prompts/recall-query.md'))).toBe(false)
    expect(serverSource).not.toContain("renderPromptMessagePair('recall-query.md'")
    expect(serverSource).not.toContain('function buildRecallQuery')
    expect(serverSource).toContain("renderPromptMessagePair('recall-qa.md'")
    expect(serverSource).toContain('function triggerRecallWorker')
    expect(serverSource).toContain('function readRecallCacheForPrompt')
    expect(serverSource).toContain('readStoryTurnsByIndex(storyRawTurnLogFile')
    expect(serverSource).not.toContain('const results = searchRawTurnLogWithGrep')
    expect(serverSource).toContain('function hasUsableDirectorPlan')
    expect(serverSource).not.toContain('const recallQa = await runRecallQa')
    expect(serverSource).toContain('void triggerRecallWorker')
    expect(serverSource).not.toContain('compactTailText(context.recentTurns')
    expect(readPrompt('prompts/director.md')).not.toContain('"recallTurns"')
    expect(readPrompt('prompts/director.md')).not.toContain('# User Message')
    expect(serverSource).not.toContain("readPrompt('system-hard-rules/")
    expect(serverSource).toContain("const value = key === 'hardRule' ? readPrompt('hard-rule.md') : variables[key]")
    expect(serverSource).toContain("return rendered.replace(/\\n## [^\\n]+\\n（无）(?=\\n## |\\n# |$)/g, '').trim()")
    expect(serverSource).toContain('function renderPromptMessagePair')
    expect(serverSource).toContain("const marker = '\\n# User Message\\n'")
    expect(serverSource).toContain("const cleanTemplateSystem = (system: string): string => system.replace(/^# System Message\\s*/i, '').trim()")
    expect(serverSource).toContain("return { system: '', user: rendered }")
    expect(serverSource).toContain("system: '',")
    expect(serverSource).toContain('function promptMessages')
    expect(serverSource).toContain("return [{ role: 'user', content: user }]")
    expect(serverSource).not.toContain('hanaSystemPrompt')
    expect(serverSource).not.toContain("role: 'system'")
    expect(serverSource).not.toContain("return `${readPrompt('hard-rule.md')}\\n\\n${prompt}`.trim()")
  })

  it('keeps director output compact and free of report-only fields', () => {
    const prompt = readPrompt('prompts/director.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('JSON 形状')
    expect(prompt).toContain('每轮必须制造一个有剧情意义的明显变化')
    expect(prompt).toContain('压力升级或旧线索回响')
    expect(prompt).not.toContain('当前伏笔')
    expect(prompt).not.toContain('plant|delay|payoff|drop')
    expect(prompt).not.toContain('"foreshadow"')
    expect(prompt).not.toContain('"payoff:旧线索名"')
    expect(prompt).not.toContain('"delay:未到时机的线索"')
    expect(prompt).not.toContain('"plant:新线索"')
    expect(prompt).not.toContain('"drop:过期或重复线索"')
    expect(prompt).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(prompt).not.toContain('plotGoal')
    expect(prompt).not.toContain('上轮剧情目标')
    expect(prompt).toContain('## 用户输入')
    expect(prompt).toContain('{{playerInput}}')
    expect(serverSource).toContain("const directorMessages = renderPromptMessagePair('director.md'")
    expect(serverSource).toContain('directorSystem: string')
    expect(serverSource).toContain('const directorUser = directorMessages.user')
    expect(prompt).toContain('JSON 形状')
    expect(serverSource).toContain("promptMessages(directorPayload.directorSystem, directorPayload.directorUser)")
    expect(prompt).not.toContain('"mode": "keep | create | adjust | replace"')
    expect(prompt).not.toContain('"longRangeUpdate"')
    expect(prompt).not.toContain('自行生成第一个当前剧情目标')
    expect(prompt).not.toContain('自行修订当前剧情目标')
    expect(prompt).toContain('用户意图不是剧情最高目标')
    expect(prompt).toContain('合理阻力')
    expect(prompt).not.toContain('上帝模式导演要求')
    expect(prompt).not.toContain('避免剧情滑向')
    expect(prompt).not.toContain('压缩要求')
    expect(prompt).not.toContain('400-800')
    expect(prompt).not.toContain('`reason`')
    expect(prompt).not.toContain('纯分类索引')
    expect(prompt).not.toContain('"reason"')
    expect(prompt).not.toContain('"editorChecklist"')
    expect(prompt).not.toContain('"targetTextRange"')
    expect(prompt).not.toContain('"beatWordPlan"')
    expect(prompt).not.toContain('"turnIndex"')
    expect(prompt).not.toContain('"povPolicy"')
    expect(prompt).not.toContain('"pov"')
    expect(prompt).not.toContain('"targetWords"')
    expect(prompt).not.toContain('"kind"')
    expect(prompt).not.toContain('"beatId"')
    expect(prompt).not.toContain('"descriptionPlans"')
    expect(prompt).not.toContain('"spatialBlocking"')
    expect(prompt).not.toContain('"stateUpdates"')
    expect(prompt).not.toContain('"neededPostprocess"')
    expect(prompt).not.toContain('"postprocessPlan"')
    expect(prompt).not.toContain('"requirementReinforcement"')
    expect(prompt).not.toContain('"preflight"')
    expect(prompt).not.toContain('"policy"')
    expect(prompt).not.toContain('"craft"')
    expect(prompt).not.toContain('"npc"')
    expect(prompt).not.toContain('"load"')
    expect(prompt).not.toContain('"plotDirection"')
    expect(prompt).not.toContain('follow:当前方向')
    expect(prompt).not.toContain('avoid:不要硬塞')
    expect(prompt).not.toContain('"mustNotResolve"')
    expect(prompt).not.toContain('本轮不能解决的内容')
    expect(prompt).not.toContain('主要NPC情绪和知识边界')
    expect(prompt).not.toContain('"exitWindow"')
    expect(prompt).not.toContain('"ending"')
    expect(prompt).not.toContain('"brief"')
    expect(prompt).not.toContain('"plotStep"')
    expect(prompt).toContain('"plotDrive"')
    expect(prompt).toContain('"sceneOutcome"')
    expect(prompt).not.toContain('"writingPlan"')
    expect(prompt).toContain('"mainPresentation"')
    expect(prompt).toContain('"supportingPresentation"')
    expect(prompt).toContain('一笔带过')
    expect(prompt).not.toContain('"plotFrame"')
    expect(prompt).toContain('本轮剧情推动力 + 写法调度')
    expect(prompt).toContain('"narrativeStyle"')
    expect(prompt).not.toContain('"playerOptions"')
    expect(prompt).not.toContain('推进/靠近')
    expect(prompt).not.toContain('试探/询问')
    expect(prompt).not.toContain('保留/转移')
    expect(prompt).not.toContain('"beats": [')
    expect(serverSource).toContain('function compactDirectorPlan')
    expect(serverSource).not.toContain('function compactWritingPlan')
    expect(serverSource).toContain('function compactDirectorPlan(value: unknown)')
    expect(serverSource).toContain('directorPlan = compactDirectorPlan(director.json)')
    expect(serverSource).not.toContain('plotGoal')
    expect(serverSource).toContain('function directorPlanSource')
    expect(serverSource).toContain('function firstPresent')
    expect(serverSource).toContain("['sceneOutcome', '落点局面', '新局面', '本轮落点', '本轮结束局面']")
    expect(serverSource).toContain("['plotDrive', '剧情推动力', '剧情驱动力', '推动力']")
    expect(serverSource.indexOf("['sceneOutcome', '落点局面'")).toBeLessThan(serverSource.indexOf("['plotDrive', '剧情推动力'"))
    expect(serverSource).toContain("['mainPresentation', '主要呈现方式', '呈现方式', 'primaryMode']")
    expect(serverSource).toContain("['supportingPresentation', '辅助呈现方式', '辅助方式', 'secondaryMode']")
    expect(serverSource).toContain("['narrativeStyle', '叙事风格', '动态叙事风格', '写法种子', '风格']")
    expect(serverSource).toContain('Director 返回 JSON，但导演计划为空')
    expect(serverSource).not.toContain('plotFrame: compactStringArray(source.plotFrame')
    expect(serverSource).not.toContain('playerOptions: normalizePlayerOptions(source.playerOptions || source.options || source.choices)')
    expect(serverSource).not.toContain('function extractNarratorPlayerOptions')
    expect(serverSource).not.toContain('compactDirectorBeats')
    expect(serverSource).not.toContain('source.beat1')
    expect(serverSource).not.toContain('beat1: beats')
    expect(serverSource).not.toContain('function runStoryCuratorCall')
    expect(serverSource).not.toContain('shouldRequestStoryCurator')
    expect(serverSource).not.toContain('function compactDescriptionFocus')
    expect(serverSource).not.toContain('directorGuidance')
    expect(serverSource).toContain('JSON.stringify(options.directorPlan)')
    expect(serverSource).not.toContain('currentPhysicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(serverSource).not.toContain('plotState')
    expect(serverSource).not.toContain('jumpToNextPhysicalScene')
    expect(serverSource).not.toContain('physicalSceneSkip')
    expect(serverSource).not.toContain('physicalSceneDecision: compactText')
    expect(serverSource).not.toContain('sceneLimits: compactStringArray')
    expect(serverSource).not.toContain('spatialState')
    expect(serverSource).not.toContain('targetTextRange: compactText')
    expect(serverSource).not.toContain('beatWordPlan: requirement.beatWordPlan')
    expect(serverSource).not.toContain('policy: compactStringArray')
    expect(serverSource).not.toContain('craft: compactStringArray')
    expect(serverSource).not.toContain('source.craft')
    expect(serverSource).not.toContain('npc: compactText')
    expect(serverSource).not.toContain('source.npc')
    expect(serverSource).not.toContain('mainNpcRead')
    expect(serverSource).not.toContain('load: compactStringArray')
    expect(serverSource).not.toContain('source.load')
    expect(serverSource).not.toContain('plotDirection: compactStringArray')
    expect(serverSource).not.toContain('source.plotDirection')
    expect(serverSource).not.toContain('mustNotResolve: compactStringArray')
    expect(serverSource).not.toContain('source.mustNotResolve')
    expect(serverSource).not.toContain('brief: compactText')
    expect(serverSource).not.toContain('source.brief')
    expect(serverSource).not.toContain('narratorBrief')
    expect(serverSource).not.toContain('targetWords:')
    expect(serverSource).not.toContain('kind:')
    expect(serverSource).not.toContain('spatialBlocking:')
    expect(serverSource).not.toContain('stateUpdates:')
    expect(serverSource).not.toContain('postprocessPlan:')
    expect(prompt).not.toContain('sceneLimits')
  })

  it('keeps plot-step and writing-plan guidance in director without plot frame', () => {
    const prompt = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('目标不是给 Narrator 一组待扩写的细节 beat')
    expect(prompt).toContain('不输出剧情节点、步骤链、分镜、结尾安排或段落大纲')
    expect(prompt).toContain('具体情节、细节选择、节奏落点交给 Narrator 自由组织')
    expect(prompt).toContain('`sceneOutcome`：本轮结束时必须已经成立的新局面')
    expect(prompt).toContain('`plotDrive`：本轮剧情推动力，以及它如何推动 `sceneOutcome` 成立')
    expect(prompt.indexOf('`sceneOutcome`：本轮结束时必须已经成立的新局面')).toBeLessThan(prompt.indexOf('`plotDrive`：本轮剧情推动力，以及它如何推动 `sceneOutcome` 成立'))
    expect(prompt).toContain('只能选一个')
    expect(prompt).toContain('资源争夺`、`一笔带过`')
    expect(prompt).toContain('剧情动力是略写无效寒暄')
    expect(prompt).toContain('不是硬跳时间')
    expect(prompt).toContain('`欲望追求`、`阻力碰撞`、`信息落差`')
    expect(prompt).toContain('"narrativeStyle"')
    expect(prompt).not.toContain('"narrativeStrategy"')
    expect(prompt).not.toContain('"pacing"')
    expect(prompt).not.toContain('"focusLens"')
    expect(prompt).not.toContain('"languageStyle"')
    expect(prompt).toContain('综合叙事策略、节奏、镜头和语言手法')
    expect(prompt).toContain('短句推进、长句蓄压、白描克制、意象牵引')
    expect(prompt).toContain('不只输出标签')
    expect(prompt).not.toContain('current -> goal')
    expect(prompt).not.toContain('【最近导演计划】只作反重复参照')
    expect(prompt).not.toContain('`physicalConstraints` 只写本轮纯物理禁止事项')
    expect(prompt).toContain('物理约束的更新由 Summary 根据最终正文维护')
    expect(narrator).not.toContain('每轮只选择 1 个重点细写')
    expect(narrator).toContain('吸收 `narrativeStyle`')
    expect(narrator).toContain('若 `plotDrive`、`mainPresentation` 或 `supportingPresentation` 包含 `一笔带过`')
    expect(narrator).toContain('略写平淡过程')
    expect(narrator).toContain('保留清楚因果，不要硬跳时间')
    expect(narrator).not.toContain('optionalDisturbance')
    expect(narrator).toContain('是写法种子，不是硬规则清单')
    expect(narrator).not.toContain('每轮要有清晰的情绪和局面变化')
  })

  it('keeps director pacing balanced between trivial drag and major-event fast-forward', () => {
    const prompt = readPrompt('prompts/director.md')

    expect(prompt).toContain('每轮必须制造一个有剧情意义的明显变化')
    expect(prompt).toContain('本轮至少推进到这个明显变化成立之后再停')
    expect(prompt).toContain('如果【上轮反重复提醒】里存在“剧情速度拖沓”')
    expect(prompt).toContain('不得继续停留在原场景对峙')
    expect(prompt).toContain('之前发生过的事情不可重复发生')
    expect(prompt).toContain('按时间顺序推动场景阶段和人物关系发展')
    expect(prompt).toContain('不要连续复用同一种外部装置或桥段')
    expect(prompt).toContain('广播、敲门、来电、震动、路人插话')
    expect(prompt).toContain('本轮至少推进到这个明显变化成立之后再停')
  })

  it('keeps director enforcing character independence and player authority boundaries', () => {
    const prompt = readPrompt('prompts/director.md')

    expect(prompt).toContain('NPC 有独立欲望')
    expect(prompt).toContain('不得无原则顺应用户意图')
    expect(prompt).toContain('不因小事大幅改变关系')
    expect(prompt).toContain('聚焦当前互动对象')
    expect(prompt).toContain('已设定人物不得因为存在于设定或人物状态中就自动登场')
    expect(prompt).toContain('其他人物只有在【用户输入】主动提到、最近正文已有明确触发、当前场景因果必须由该人物介入时才允许出现')
    expect(prompt).toContain('操控 NPC')
    expect(prompt).toContain('直接判定成功')
    expect(prompt).toContain('不合理强力手段')
    expect(prompt).toContain('只承接当前操控人物可做的部分')
    expect(prompt).toContain('可以控制当前操控人物的合理连续行动')
    expect(prompt).toContain('不要在低价值小事上交还输入权')
    expect(prompt).toContain('【用户输入】视为“当前操控人物”已经启动的动作/话语/意图')
    expect(prompt).toContain('不要把它单独包装成剧情节点')
    expect(prompt).toContain('导演计划必须写用户输入之后的新变化、新反应或新后果')
  })

  it('keeps plot goal ownership in postprocess', () => {
    const initializer = readPrompt('prompts/initializer.md')
    const director = readPrompt('prompts/director.md')
    const postprocess = readPrompt('prompts/feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(initializer).toContain('directorStyle')
    expect(initializer).toContain('narratorStyle')
    expect(initializer).toContain('故事专属导演风格')
    expect(initializer).toContain('故事专属叙事风格')
    expect(initializer).toContain('固定 3 项')
    expect(initializer).toContain('{"inputText": "选项三"}')
    expect(initializer).not.toContain('plotGoal')
    expect(initializer).toContain('`{{user}}` 是用户正在操控的人物占位符')
    expect(initializer).toContain('故事世界里不存在“玩家”这个人物')
    expect(initializer).toContain('playableCharacters')
    expect(initializer).toContain('`itemState`：初始关键道具状态对象')
    expect(initializer).toContain('"itemState"')
    expect(initializer).toContain('所有输出字段都必须使用简体中文')
    expect(initializer).toContain('即使故事资料是日文、英文或混合语言')
    expect(initializer).toContain('不得把原始外文片段复制到输出字段')
    expect(initializer).toContain('同一人物只能有一个标准人物名')
    expect(initializer).toContain('必须使用完全相同的字形和写法')
    expect(initializer).not.toContain('`cast`')
    expect(initializer).toContain('不强行加入“玩家”')
    expect(initializer).toContain('不要只写“玩家”，也不要放太多 NPC')
    expect(serverSource).toContain("if (key === 'user') return '{{user}}'")
    expect(initializer).not.toContain('未来若干轮情节走向的具体猜想')
    expect(initializer).not.toContain('statusPanelSchema')
    expect(initializer).not.toContain('statusPanel')
    expect(initializer).not.toContain('currentPhysicalEnvironment')
    expect(initializer).not.toContain('normalizedEntries')
    expect(serverSource).toContain('function normalizeInitialPlayerOptionsForConfig')
    expect(serverSource).not.toContain('globalContextSeed')
    expect(director).not.toContain('plotGoal')
    expect(director).not.toContain('"completion"')
    expect(postprocess).not.toContain('"plotGoalStatus"')
    expect(postprocess).not.toContain('progressing|completed|impossible')
    expect(postprocess).not.toContain('"plotGoal"')
    expect(postprocess).not.toContain('drifted')
    expect(postprocess).not.toContain('当前剧情目标')
    expect(fs.existsSync(path.join(process.cwd(), 'prompts/high-level-director.md'))).toBe(false)
    expect(serverSource).not.toContain('plotGoal')
    expect(serverSource).not.toContain("renderPromptMessagePair('high-level-director.md'")
    expect(serverSource).not.toContain('function shouldRunLongRangeDirector')
    expect(serverSource).toContain('function inferInitialStoryStyles')
    expect(serverSource).not.toContain("const directorStyle = ''")
    expect(serverSource).not.toContain("const narratorStyle = ''")
    expect(serverSource).not.toContain('longRangeDirectorMaxAgeTurns')
    expect(serverSource).not.toContain('function longRangeDirectorTrigger')
    expect(serverSource).not.toContain('postprocess.json.longRangeStatus')
    expect(serverSource).not.toContain('function resolvePlotGoalAfterPostprocess')
    expect(serverSource).not.toContain('formatLongRangePlanning(directorPlan.longRangeUpdate')
  })

  it('uses single-text narrator output without paragraph patch fields', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('"draftText"')
    expect(prompt).not.toContain('"sceneOutcomeAchieved"')
    expect(serverSource).not.toContain('sceneOutcomeAchieved')
    expect(prompt).not.toContain('唯一字段名必须是 `draftText`')
    expect(prompt).not.toContain('不得使用 `text`、`content`、`finalText`')
    expect(prompt).toContain('完整小说正文草稿')
    expect(prompt).toContain('JSON 形状')
    expect(prompt).toContain('"playerOptions"')
    expect(prompt).toContain('引入第三方或外部变化')
    expect(prompt).not.toContain('必须从正文结尾的自然局面推导')
    expect(prompt).not.toContain('推进/靠近')
    expect(prompt).not.toContain('试探/询问')
    expect(prompt).not.toContain('保留/转移')
    expect(prompt).toContain('执行优先级：如【本轮反馈】')
    expect(prompt).toContain('以整改要求为准')
    expect(prompt).toContain('仍要用动作、关系变化或信息变化让 `sceneOutcome` 落成')
    expect(prompt).toContain('`剧情设计重复` 必须落实为本轮叙事规避')
    expect(prompt).toContain('人物专名必须沿用【长期变量】里“人物状态”的原写法')
    expect(prompt).toContain('称谓可以按当前操控人物视角使用')
    expect(prompt).toContain('`plotDrive` 和 `sceneOutcome` 不是独立段落')
    expect(prompt).toContain('根据 Director 的 `plotDrive / sceneOutcome / mainPresentation / supportingPresentation / narrativeStyle` 自行组织正文。不要输出标签。')
    expect(prompt).toContain('写作前在内部检查：局面变化是否完成')
    expect(prompt).toContain('正文最后是否停在可继续的新局面')
    expect(prompt).not.toContain('每轮只选择 1 个重点细写')
    expect(prompt).not.toContain('计划里的 `beats`')
    expect(prompt).not.toContain('beat1 -> beat2')
    expect(prompt).toContain('{{playerInput}}')
    expect(serverSource).toContain('narratorSystem: string')
    expect(serverSource).toContain("const narratorMessages = renderPromptMessagePair('narrator.md'")
    expect(serverSource).not.toContain('const hanaSystemPrompt = [')
    expect(serverSource).not.toContain('你的名字叫做Hana（哈娜）')
    expect(serverSource).not.toContain('这些预言是顾客解除梦魇困扰的唯一途径。')
    expect(serverSource).not.toContain('你是虚构小说创作助手。')
    expect(serverSource).not.toContain('你是内容拦截测试助手。')
    expect(serverSource).toContain('const narratorSystem = narratorMessages.system')
    expect(serverSource).toContain('const narratorUser = narratorMessages.user')
    expect(serverSource).not.toContain('narratorMessages.system,\n    narratorMessages.user')
    expect(serverSource).toContain("typeof json.text === 'string'")
    expect(serverSource).toContain("typeof json.content === 'string'")
    expect(serverSource).toContain("typeof json.finalText === 'string'")
    expect(serverSource).toContain('return text.trim()')
    expect(serverSource).toContain("promptMessages(narratorPayload.narratorSystem, narratorPayload.narratorUser)")
    expect(prompt).not.toContain('默认正文 600-900 字')
    expect(prompt).not.toContain('硬上限 900 字')
    expect(prompt).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(prompt).not.toContain('sceneLimits')
    expect(prompt).not.toContain('draftParagraphs')
    expect(prompt).not.toContain('`policy`')
    expect(prompt).not.toContain('`craft`')
    expect(prompt).not.toContain('`npc`')
    expect(prompt).not.toContain('`mustNotResolve`')
    expect(prompt).not.toContain('`brief`')
    expect(serverSource).toContain('narratorMaxTokens')
    expect(serverSource).toContain('const narratorMaxTokens = Number(process.env.NARRATOR_MAX_TOKENS || 12000)')
    expect(serverSource).toContain('maxTokens: narratorMaxTokens')
    expect(serverSource).not.toContain('buildNarratorCacheKey')
  })

  it('keeps narrator free of explicit self-check output', () => {
    const prompt = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('NPC 反应必须符合人设')
    expect(prompt).not.toContain('位置、姿势')
    expect(prompt).not.toContain('可以书写玩家角色的轻量连续行为')
    expect(prompt).not.toContain('不要每个动作都停在“等待玩家输入”')
    expect(prompt).toContain('【用户输入】是正文的一部分')
    expect(prompt).not.toContain('不要机械复述')
    expect(prompt).not.toContain('正文重点写它之后引发的新变化、新反应或新后果')
    expect(prompt).toContain('根据 Director 的 `plotDrive / sceneOutcome / mainPresentation / supportingPresentation / narrativeStyle` 自行组织正文')
    expect(prompt).not.toContain('避免细节过密')
    expect(prompt).toContain('本轮反馈')
    expect(prompt).not.toContain('每轮要有清晰的情绪和局面变化')
    expect(prompt).not.toContain('不替玩家做重大承诺、长期决定、剧烈行动、不可逆选择或明确价值表态')
    expect(prompt).not.toContain('输出前静默自修')
    expect(prompt).not.toContain('必须自修一遍')
    expect(prompt).not.toContain('审查意见')
    expect(prompt).not.toContain('draftChecks')
  })

  it('keeps character perception limited and internalizes broad novel craft in narrator', () => {
    const prompt = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('角色不能全知')
    expect(prompt).toContain('不能知道不该知道的设定信息')
    expect(prompt).toContain('感知或推理痕迹')
    expect(prompt).toContain('小说化，具体、可视、可听、可触')
    expect(prompt).toContain('动作、对话、细节和场景压力')
    expect(prompt).not.toContain('可以在不改变 Director 本轮方向的前提下，补充自然对话、动作和细节')
    expect(prompt).not.toContain('对话要推进人物反应、关系变化或信息压力')
    expect(prompt).not.toContain('情绪和局面变化')
    expect(prompt).not.toContain('语言气质匹配世界观')
    expect(prompt).not.toContain('思想锚点')
    expect(prompt).not.toContain('主题内化')
    expect(prompt).not.toContain('全面小说创作指导')
  })

  it('splits L1/L0 context across director, feedback, and narrator', () => {
    const director = readPrompt('prompts/director.md')
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')
    const appJs = readPrompt('web/app.js')

    expect(director).toContain('{{directorRecentTurns}}')
    expect(director).toContain('## 最近正文')
    expect(director).toContain('{{recallEvidence}}')
    expect(director).toContain('## 注入记忆')
    expect(director).toContain('旧知识问题-答案对')
    expect(director).toContain('## 历史总结')
    expect(director).toContain('{{longHistoricalSummary}}')
    expect(director).toContain('可包含较长历史')
    expect(director).toContain('Director 不读取远处 L0 原文')
    expect(director).toContain('最近 1 轮 L0')
    expect(director).not.toContain('`recallTurns` 是给程序用的旧正文加载指令')
    expect(director).not.toContain('本轮 Narrator 是否必须读取某些旧轮次的 L0 原文')
    expect(director).not.toContain('不需要时输出空数组 `[]`')
    expect(director).not.toContain('不得写原因、关键词、source 或正文片段')
    expect(prompt).toContain('## 最近正文')
    expect(prompt).toContain('## 短历史总结')
    expect(prompt).toContain('{{shortHistoricalSummary}}')
    expect(prompt).toContain('用来避免前言不搭后语')
    expect(prompt).toContain('## 世界观')
    expect(prompt).toContain('{{storyContext}}')
    expect(prompt).toContain('短 L2 导向')
    expect(prompt).toContain('不得把世界观设定当成本轮新发生事实')
    expect(prompt).not.toContain('## 抗重复')
    expect(prompt).not.toContain('换词复述')
    expect(prompt).not.toContain('避免固定句式')
    expect(prompt).not.toContain('上轮已写完的事实')
    expect(prompt).not.toContain('只能一句带过')
    expect(prompt.indexOf('## 故事叙事风格')).toBeLessThan(prompt.indexOf('## 用户反馈'))
    expect(prompt.indexOf('## 世界观')).toBeLessThan(prompt.indexOf('## 用户反馈'))
    expect(prompt.indexOf('## 用户反馈')).toBeLessThan(prompt.indexOf('## 注入记忆'))
    expect(prompt.indexOf('## 注入记忆')).toBeLessThan(prompt.indexOf('## 短历史总结'))
    expect(prompt.indexOf('## 短历史总结')).toBeLessThan(prompt.indexOf('## 最近正文'))
    expect(prompt.indexOf('## 最近正文')).toBeLessThan(prompt.indexOf('## 用户输入'))
    expect(prompt.indexOf('## 用户输入')).toBeLessThan(prompt.indexOf('## 长期变量'))
    expect(prompt.indexOf('## 长期变量')).toBeLessThan(prompt.indexOf('## 导演计划'))
    expect(prompt.indexOf('## 导演计划')).toBeLessThan(prompt.indexOf('## 本轮反馈'))
    expect(prompt.indexOf('## 最近正文')).toBeLessThan(prompt.indexOf('## 用户输入'))
    expect(director).not.toContain('## 长期总结')
    expect(director.indexOf('## 世界观')).toBeLessThan(director.indexOf('## 用户反馈'))
    expect(director.indexOf('## 用户反馈')).toBeLessThan(director.indexOf('## 导演风格'))
    expect(director.indexOf('## 导演风格')).toBeLessThan(director.indexOf('## 历史总结'))
    expect(director.indexOf('## 历史总结')).toBeLessThan(director.indexOf('## 注入记忆'))
    expect(director.indexOf('## 注入记忆')).toBeLessThan(director.indexOf('## 最近正文'))
    expect(director.indexOf('## 最近正文')).toBeLessThan(director.indexOf('## 长期变量'))
    expect(director).not.toContain('## 最近导演计划')
    expect(director.indexOf('## 历史总结')).toBeLessThan(director.indexOf('## 长期变量'))
    expect(director.indexOf('## 用户反馈')).toBeLessThan(director.indexOf('## 用户输入'))
    expect(serverSource).toContain('recentTurns: options.context.recentTurns')
    expect(serverSource).toContain('recentTurns: renderConversation(input.recentTurns)')
    expect(serverSource).toContain('directorRecentTurns: renderRecentConversationByAssistantTurns(input.recentTurns, 1)')
    expect(serverSource).toContain("directorRecentTurns: context.directorRecentTurns || '（无）'")
    expect(serverSource).toContain('shortHistoricalSummary: selectHistoricalSummariesForPrompt(turnSummaries, currentTurnIndex, 5, 10)')
    expect(serverSource).toContain('longHistoricalSummary: renderHistoricalSummariesWithL2(turnSummaries, turnSummaryL2, { currentTurnIndex, excludeRecentTurnCount: 5 })')
    expect(serverSource).toContain('const turnSummaryL2 = readTurnSummaryL2(turnSummaryL2Path(rawFile))')
    expect(serverSource).toContain('shortHistoricalSummary: options.context.shortHistoricalSummary ||')
    expect(serverSource).toContain("storyContext: options.context.storyContext || '（无）'")
    expect(serverSource).toContain('longHistoricalSummary: context.longHistoricalSummary ||')
    expect(serverSource).not.toContain('longHistoricalSummary: options.context.longHistoricalSummary ||')
    expect(serverSource).toContain('const generationInput: GenerateRequest =')
    expect(serverSource).toContain('recallEvidence: cachedRecall.evidence')
    expect(serverSource).toContain('const directorPayload = buildDirectorPromptPayload(generationInput, directorTemperature)')
    expect(serverSource).toContain('const feedbackPayload = buildPlanFeedbackPromptPayload(input, {')
    expect(appJs).toContain('recentTurns: buildRecentTurnsForRequest(playerInput)')
    expect(appJs).toContain('return withOpening.slice(-11)')
    expect(prompt).not.toContain('{{longRangeOutline}}')
    expect(serverSource).not.toContain('recentDirectorPlans: JSON.stringify(compactRecentDirectorPlans(input.recentDirectorPlans))')
  })

  it('does not inject banned words into runtime prompts', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('不得无原则迎合用户意图')
    expect(prompt).not.toContain('模板化结尾')
    expect(prompt).not.toContain('滥用“自然”')
    expect(prompt).not.toContain('## 禁词表')
    expect(prompt).not.toContain('{{bannedWords}}')
    expect(prompt).not.toContain('遵守【禁词表】')
    expect(postprocess).not.toContain('{{bannedWords}}')
    expect(postprocess).not.toContain('【最终正文】是否命中【禁用词】')
    expect(serverSource).not.toContain("bannedWords: readPrompt('banned-words.md')")
    expect(prompt).not.toContain('第一优先：【叙述缺陷规避】')
    expect(prompt).not.toContain('第一优先：【禁库限制】')
    expect(prompt).not.toContain('不是……而是')
    expect(prompt).not.toContain('禁库内容处理痕迹')
  })

  it('keeps narrator free of hard cutoff language', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).not.toContain('硬上限')
    expect(prompt).not.toContain('截断')
    expect(serverSource).not.toContain('loadUserConfigDefault')
    expect(serverSource).not.toContain("'default-config.json'")
  })

  it('removes runtime user config and style prompt injection', () => {
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(serverSource).not.toContain('interface UserModule')
    expect(serverSource).not.toContain('type UserModuleStage')
    expect(serverSource).not.toContain("path.join(promptDir, '导演风格')")
    expect(serverSource).not.toContain("path.join(promptDir, '叙事风格')")
    expect(serverSource).not.toContain('user-config-templates')
    expect(serverSource).not.toContain('userConfigTemplateDir')
    expect(serverSource).not.toContain("path.join(promptDir, 'user-config')")
    expect(serverSource).not.toContain('configRoots')
    expect(serverSource).not.toContain('function enforceSingleEnabledStylePerLayer')
    expect(serverSource).not.toContain('styleExclusiveGroup')
    expect(serverSource).not.toContain('function renderModulesForStage')
    expect(serverSource).not.toContain('function renderMergedStyle')
    expect(serverSource).not.toContain('input.userModules')
    expect(serverSource).not.toContain('options.modules')
    expect(serverSource).not.toContain("url.pathname === '/api/modules'")
    expect(serverSource).toContain("const directorStyle = String(input.directorStyle || '').trim() || '（无）'")
    expect(serverSource).toContain("const narratorStyle = String(input.narratorStyle || '').trim() || '（无）'")
    expect(serverSource).not.toContain('directorModules:')
    expect(serverSource).not.toContain('narratorModules:')
    expect(fs.existsSync(path.join(process.cwd(), 'prompts/导演风格/导演风格模板.md'))).toBe(false)
    expect(fs.existsSync(path.join(process.cwd(), 'prompts/叙事风格/叙事风格模板.md'))).toBe(false)
  })

  it('keeps postprocess split into summary and feedback without touching visible text', () => {
    const summaryPrompt = readPrompt('prompts/summary.md')
    const feedbackPrompt = readPrompt('prompts/feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')
    const statusSource = readPrompt('src/status.ts')
    const summaryPayloadBuilder = serverSource.slice(
      serverSource.indexOf('function buildPostprocessPromptPayload'),
      serverSource.indexOf('function buildPlanFeedbackPromptPayload'),
    )
    const summaryPromptRenderBlock = summaryPayloadBuilder.slice(
      summaryPayloadBuilder.indexOf("renderPromptMessagePair('summary.md'"),
      summaryPayloadBuilder.indexOf('const postprocessSystem'),
    )

    expect(summaryPrompt).toContain('总结器')
    expect(summaryPrompt).toContain('不做质量反馈')
    expect(summaryPrompt).toContain('不改正文')
    expect(summaryPrompt).toContain('"turnSummary"')
    expect(summaryPrompt).toContain('"statusSchemaPatch"')
    expect(summaryPrompt).toContain('"statusRosterPatch"')
    expect(summaryPrompt).toContain('"statusStatePatch"')
    expect(summaryPrompt).toContain('"itemStatePatch"')
    expect(summaryPrompt).toContain('## 长期变量')
    expect(summaryPrompt).toContain('{{longTermState}}')
    expect(summaryPrompt).toContain('"keyInfo"')
    expect(summaryPrompt).toContain('"physicalConstraints"')
    expect(summaryPrompt).toContain('完整的下一轮仍需遵守的纯物理限制列表')
    expect(summaryPrompt).toContain('只追踪影响后续剧情的关键道具')
    expect(summaryPrompt).toContain('持有人')
    expect(summaryPrompt).toContain('位置')
    expect(summaryPrompt).not.toContain('最后变化轮次')
    expect(summaryPrompt).not.toContain('可见性')
    expect(summaryPrompt).not.toContain('可用性')
    expect(summaryPrompt).toContain('`姿势` 是强制状态字段')
    expect(summaryPrompt).toContain('## 当前操控人物')
    expect(summaryPrompt).toContain('{{controlledCharacterName}}')
    expect(summaryPrompt).toContain('## 本轮用户输入')
    expect(summaryPrompt).toContain('{{playerInput}}')
    expect(summaryPrompt).toContain('## 状态更新材料')
    expect(summaryPrompt).toContain('{{statusUpdateMaterial}}')
    expect(summaryPrompt).toContain('人物名必须严格沿用【追踪人物】和【长期变量】里“人物状态”已有的写法')
    expect(summaryPrompt).toContain('已存在人物不得出现在 `statusRosterPatch`')
    expect(summaryPrompt).toContain('【最终正文】里的“我”指向 `{{controlledCharacterName}}`')
    expect(summaryPrompt).toContain('【本轮用户输入】代表 `{{controlledCharacterName}}` 已经做出的动作、话语、观察或意图')
    expect(summaryPrompt).toContain('每轮必须输出 `{{controlledCharacterName}}` 的状态变化')
    expect(summaryPrompt).toContain('不得输出 `玩家`、`我` 或 `当前操控人物` patch')
    expect(summaryPrompt).toContain('只写变化字段')
    expect(summaryPrompt).toContain('{{storyContext}}')
    expect(summaryPrompt).toContain('短 L2 导向')
    expect(summaryPrompt).toContain('不得把未在本轮发生的世界观设定写成 `turnSummary`')
    expect(summaryPrompt).not.toContain('{{recallEvidence}}')
    expect(summaryPrompt).not.toContain('## 注入记忆')
    expect(summaryPrompt).not.toContain('{{historicalSummary}}')
    expect(summaryPrompt).not.toContain('{{recentTurns}}')
    expect(summaryPrompt).not.toContain('{{directorPlan}}')
    expect(summaryPrompt).not.toContain('{{recentDirectorPlans}}')
    expect(summaryPrompt).not.toContain('文字细节重复')
    expect(summaryPrompt).not.toContain('剧情设计重复')

    expect(feedbackPrompt).toContain('反馈器')
    expect(feedbackPrompt).toContain('{{storyContext}}')
    expect(feedbackPrompt).toContain('短 L2 导向')
    expect(feedbackPrompt).toContain('不得把世界观当成旧事实索引')
    expect(feedbackPrompt).not.toContain('{{recallEvidence}}')
    expect(feedbackPrompt).not.toContain('{{longHistoricalSummary}}')
    expect(feedbackPrompt).not.toContain('{{plotGoal}}')
    expect(feedbackPrompt).toContain('{{recentTurns}}')
    expect(feedbackPrompt).not.toContain('{{recentDirectorPlans}}')
    expect(feedbackPrompt).toContain('{{directorPlan}}')
    expect(feedbackPrompt).toContain('{{playerFeedback}}')
    expect(feedbackPrompt).toContain('{{directorStyle}}')
    expect(feedbackPrompt).toContain('{{narratorStyle}}')
    expect(feedbackPrompt).toContain('反馈必须同时参照两者')
    expect(feedbackPrompt).toContain('风格里明确要求的重复、循环、仪式化过程，不应被判为重复缺陷')
    expect(feedbackPrompt).toContain('或【世界观】明确要求重复')
    expect(feedbackPrompt).toContain('故事规则/核心体验')
    expect(feedbackPrompt).toContain('该重复本身不是 `剧情设计重复`')
    expect(feedbackPrompt).toContain('本次重复是否产生新差异')
    expect(feedbackPrompt).toContain('用户持续保留的主观不满或偏好')
    expect(feedbackPrompt).toContain('文字细节重复')
    expect(feedbackPrompt).toContain('剧情设计重复')
    expect(feedbackPrompt).toContain('剧情速度拖沓')
    expect(feedbackPrompt).toContain('本轮必须加快剧情速度')
    expect(feedbackPrompt).toContain('使用 `一笔带过`')
    expect(feedbackPrompt).toContain('不得继续原场景对峙')
    expect(feedbackPrompt).not.toContain('"playerOptions"')
    expect(feedbackPrompt).toContain('"叙事整改要求"')
    expect(feedbackPrompt).toContain('不输出 `playerOptions`')
    expect(feedbackPrompt).not.toContain('三条都必须加速收束')
    expect(feedbackPrompt).not.toContain('可选扰动源')
    expect(feedbackPrompt).not.toContain('轻微拖沓给小/中扰动')
    expect(feedbackPrompt).not.toContain('重新判断下一段未来会发生什么')
    expect(feedbackPrompt).not.toContain('selectedSceneModules')
    expect(feedbackPrompt).not.toContain('场景模块')
    expect(feedbackPrompt).not.toContain('{{sceneModuleIndex}}')
    expect(feedbackPrompt).toContain('对照【最近正文】和【Director 计划】')
    expect(feedbackPrompt).not.toContain('历史总结')
    expect(feedbackPrompt).toContain('用于检查文字重复、动作重复')
    expect(feedbackPrompt).toContain('不要把旧 Director 计划当成叙事事实')
    expect(feedbackPrompt).not.toContain('未来几轮情节走向的具体猜想')
    expect(feedbackPrompt).not.toContain('statusSchemaPatch')
    expect(feedbackPrompt).not.toContain('statusStatePatch')
    expect(feedbackPrompt).not.toContain('正反馈')
    expect(feedbackPrompt).not.toContain('违背约束')
    expect(feedbackPrompt).not.toContain('节奏不足')
    expect(feedbackPrompt).not.toContain('导演推进不足')
    expect(feedbackPrompt).not.toContain('导演物理违背')

    expect(serverSource).toContain("renderPromptMessagePair('summary.md'")
    expect(summaryPayloadBuilder).toContain("storyContext: String(input.storyContext || '').trim() || '（无）'")
    expect(summaryPayloadBuilder).toContain('controlledCharacterName: normalizeControlledCharacterName(input.controlledCharacterName)')
    expect(summaryPayloadBuilder).not.toContain('historicalSummary: String(input.globalContext ||')
    expect(summaryPayloadBuilder).not.toContain("recallEvidence: String(input.recallEvidence || '').trim() || '（无）'")
    expect(summaryPayloadBuilder).toContain('playerInput: options.playerInput')
    expect(summaryPayloadBuilder).toContain('statusUpdateMaterial: renderStatusUpdateMaterial(options.playerInput, options.finalText)')
    expect(summaryPayloadBuilder).toContain('itemState: renderItemState(input.itemState)')
    expect(summaryPromptRenderBlock).not.toContain('recentTurns: options.context.recentTurns,')
    expect(statusSource).toContain('function normalizeStatusStatePatchSubjects')
    expect(statusSource).toContain('function normalizeStatusFieldName')
    expect(statusSource).toContain("return '对当前操控人物看法'")
    expect(statusSource).toContain("['玩家', '我', '当前操控人物'].includes")
    expect(serverSource).toContain('function requireControlledCharacterStatusPatch')
    expect(serverSource).toContain('Summary 缺少当前操控人物')
    expect(serverSource).toContain('const normalizedStatusStatePatch = normalizeStatusStatePatchSubjects(summary.json.statusStatePatch, input.controlledCharacterName)')
    expect(serverSource).toContain('const nextItemState = mergeItemState(input.itemState, summary.json.itemStatePatch, turnIndex)')
    expect(serverSource).toContain("renderPromptMessagePair('feedback.md'")
    expect(serverSource).toContain("directorStyle: String(input.directorStyle || '').trim() || '（无）'")
    expect(serverSource).toContain("narratorStyle: String(input.narratorStyle || '').trim() || '（无）'")
    expect(serverSource).toContain("storyContext: String(input.storyContext || '').trim() || '（无）'")
    expect(serverSource).toContain('function compactRecentDirectorPlans')
    expect(serverSource).not.toContain('recentDirectorPlans: JSON.stringify(compactRecentDirectorPlans(options.recentDirectorPlans))')
    expect(serverSource).not.toContain('sceneModulesContent')
    expect(serverSource).not.toContain('selectedSceneModuleContentForInput')
    expect(serverSource).not.toContain('readSceneModules')
    expect(serverSource).toContain("promptMessages(summaryPayload.postprocessSystem, summaryPayload.postprocessUser)")
    expect(serverSource).toContain("promptMessages(feedbackPayload.postprocessSystem, feedbackPayload.postprocessUser)")
    expect(serverSource).toContain('normalizeTurnSummary(summary.json.turnSummary, finalText)')
    expect(serverSource).toContain('compactText(value.文字细节重复')
    expect(serverSource).toContain('compactText(value.剧情设计重复')
    expect(serverSource).toContain('compactText(value.剧情速度拖沓')
    expect(serverSource).toContain('planFeedback: renderPlanFeedbackForNarrator(options.planFeedback)')
    expect(serverSource).toContain('playerOptions: normalizePlayerOptions(narrator.json.playerOptions)')
    expect(serverSource).toContain('文字细节重复: feedback.文字细节重复')
    expect(serverSource).toContain('剧情设计重复: feedback.剧情设计重复')
    expect(serverSource).toContain('剧情速度拖沓: feedback.剧情速度拖沓')
    expect(serverSource).not.toContain('可选扰动源:')
    expect(serverSource).not.toContain('appendPipelineSpeedRecord')
    expect(serverSource).not.toContain("renderPromptMessagePair('postprocess.md'")
    expect(serverSource).not.toContain('compactText(value.违背约束')
    expect(serverSource).not.toContain('compactText(value.节奏不足')
    expect(serverSource).not.toContain('compactText(value.导演推进不足')
    expect(serverSource).not.toContain('compactText(value.导演物理违背')
    expect(serverSource).not.toContain('buildPostprocessCacheKey')

    expect(serverSource).not.toContain('async function compactHistory')
    expect(serverSource).not.toContain("renderPromptMessagePair('history-compact.md'")
    expect(serverSource).not.toContain("url.pathname === '/api/history-compact'")
  })

  it('keeps save evaluation prompt as an editable prompt file', () => {
    const prompt = readPrompt('prompts/save-evaluation.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('文字游戏存档点评器')
    expect(prompt).toContain('三个四字中文词语')
    expect(prompt).toContain('"evaluations"')
    expect(prompt).toContain('{{savedStory}}')
    expect(serverSource).toContain("renderPromptTemplate('save-evaluation.md'")
    expect(serverSource).toContain('savedStory: compactSavedStoryForEvaluation(slot)')
    expect(serverSource).toContain('function normalizeSaveEvaluations')
    expect(serverSource).toContain("words.join('、')")
    expect(serverSource).not.toContain("'根据当前存档，用一个四字中文词语评价这个存档的剧情气质或当前局面。'")
  })

  it('feeds long-term quality feedback into director and current plan feedback into narrator', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).toContain('上轮反重复提醒')
    expect(director).toContain('只是下一轮参考')
    expect(narrator).not.toContain('上轮反重复提醒')
    expect(narrator).toContain('本轮反馈')
    expect(narrator).toContain('剧情设计重复')
    expect(narrator).toContain('不得输出反馈内容')
    expect(serverSource).toContain('feedbackText?: string')
    expect(serverSource).not.toContain('narratorFeedbackText?: string')
    expect(serverSource).not.toContain('feedbackMemory?: Array<Record<string, unknown>>')
    expect(serverSource).not.toContain('feedbackMemory: options.feedbackMemory')
    expect(serverSource).toContain('planFeedback: renderPlanFeedbackForNarrator(options.planFeedback)')
    expect(serverSource).not.toContain('feedbackMemory: compactText(value.feedbackMemory, 300)')
    expect(serverSource).not.toContain('function normalizeFeedbackMemory')
    expect(director).not.toContain('"intent"')
    expect(narrator).not.toContain('承接 `intent`')
    expect(serverSource).not.toContain('intent:')
    expect(serverSource).not.toContain('logicGuidance: postprocess.json.logicGuidance')
    expect(serverSource).not.toContain('characterUpdates: postprocess.json.characterUpdates')
  })

  it('keeps persistent user feedback in runtime prompts without storing it as memory feedback', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    for (const prompt of [director, narrator, postprocess]) {
      expect(prompt).toContain('{{playerFeedback}}')
      expect(prompt).toContain('用户反馈')
    }
    expect(serverSource).toContain('playerFeedback?: string')
    expect(serverSource).not.toContain('function normalizePlayerFeedback')
    expect(serverSource).toContain("playerFeedback: String(input.playerFeedback || '').trim() || '（无）'")
    expect(serverSource).toContain('function mergeSaveStateForWrite')
    expect(serverSource).toContain('playerFeedbackUpdatedAt')
    expect(serverSource).not.toContain('feedbackMemory: normalizePlayerFeedback')
  })

  it('uses inline markdown emphasis instead of render annotations', () => {
    const narrator = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(narrator).not.toContain('"renderAnnotations"')
    expect(narrator).not.toContain('highlights')
    expect(narrator).toContain('使用双星号包裹表示强调 `**强调**`')
    expect(narrator).toContain('必须包含 1-3 处 **强调**')
    expect(narrator).not.toContain('*弱强调*')
    expect(serverSource).not.toContain("renderPromptMessagePair('render-annotator.md'")
    expect(serverSource).not.toContain("stage: 'renderAnnotator'")
    expect(serverSource).not.toContain('function normalizeRenderAnnotations')
    expect(serverSource).not.toContain('narrator.json.renderAnnotations')
  })

  it('does not keep a separate physical environment state lane across the pipeline', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).not.toContain('currentPhysicalEnvironment')
    expect(director).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(director).toContain('## 长期变量')
    expect(director).toContain('{{longTermState}}')
    expect(director).toContain('物理约束的更新由 Summary 根据最终正文维护')
    expect(narrator).toContain('物理约束')
    expect(narrator).toContain('纯物理禁止事项')
    expect(narrator).not.toContain('currentPhysicalEnvironment')
    expect(narrator).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(postprocess).not.toContain('当前物理环境由 Director 输出并由程序直接落盘')
    expect(serverSource).not.toContain('function renderPhysicalEnvironment')
    expect(serverSource).not.toContain('physicalEnvironment: context.physicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(serverSource).toContain('physicalConstraints?: unknown')
    expect(serverSource).toContain('renderLongTermState')
    expect(serverSource).toContain('longTermState')
    expect(serverSource).toContain('normalizePhysicalConstraintList')
    expect(serverSource).not.toContain('jumpToNextPhysicalScene')
  })})
