import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readPrompt(relativePath: string): string {
  return fs.readFileSync(path.join(process.cwd(), relativePath), 'utf-8')
}

describe('prompt contracts', () => {
  it('keeps compact hard rules as an explicit input block in every agent prompt', () => {
    const serverSource = readPrompt('scripts/web-server.ts')
    const hardRule = readPrompt('prompts/hard-rule.md')
    const agentPrompts = [
      'prompts/initializer.md',
      'prompts/director.md',
      'prompts/narrator.md',
      'prompts/postprocess-summary.md',
      'prompts/postprocess-feedback.md',
    ].map(readPrompt)

    expect(fs.existsSync(path.join(process.cwd(), 'prompts/system-hard-rules'))).toBe(false)
    expect(hardRule.trim()).toBeTruthy()
    for (const prompt of agentPrompts) {
      expect(prompt).toContain('# System Message')
      expect(prompt).toContain('# User Message')
      expect(prompt).toContain('## Hard Rule')
      expect(prompt).toContain('{{hardRule}}')
      const [systemBlock = '', userBlock = ''] = prompt.split('\n# User Message\n')
      expect(systemBlock).not.toContain('## Hard Rule')
      expect(systemBlock).not.toContain('{{hardRule}}')
      expect(userBlock.trimStart()).toContain('## Hard Rule\n{{hardRule}}')
      expect(systemBlock).not.toContain('{{storyContext}}')
      expect(systemBlock).not.toContain('{{playerInput}}')
      expect(systemBlock).not.toContain('{{characterStatus}}')
      expect(systemBlock).not.toContain('{{directorPlan}}')
      expect(systemBlock).not.toContain('{{finalText}}')
    }
    expect(readPrompt('prompts/director.md')).toContain('# User Message')
    expect(serverSource).not.toContain("readPrompt('system-hard-rules/")
    expect(serverSource).toContain("const value = key === 'hardRule' ? readPrompt('hard-rule.md') : variables[key]")
    expect(serverSource).toContain("return rendered.replace(/\\n## [^\\n]+\\n（无）(?=\\n## |\\n# |$)/g, '').trim()")
    expect(serverSource).toContain('function renderPromptMessagePair')
    expect(serverSource).toContain("const marker = '\\n# User Message\\n'")
    expect(serverSource).toContain("const cleanTemplateSystem = (system: string): string => system.replace(/^# System Message\\s*/i, '').trim()")
    expect(serverSource).toContain("return { system: '', user: rendered }")
    expect(serverSource).toContain("system: '',")
    expect(serverSource).toContain('function promptMessages')
    expect(serverSource).toContain("return [{ role: 'user', content: user }]")
    expect(serverSource).not.toContain('hanaSystemPrompt')
    expect(serverSource).not.toContain("role: 'system'")
    expect(serverSource).not.toContain("return `${readPrompt('hard-rule.md')}\\n\\n${prompt}`.trim()")
  })

  it('keeps director output compact and free of report-only fields', () => {
    const prompt = readPrompt('prompts/director.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('JSON 形状')
    expect(prompt).toContain('每轮必须制造一个有剧情意义的明显变化')
    expect(prompt).toContain('压力升级或旧线索回响')
    expect(prompt).not.toContain('当前伏笔')
    expect(prompt).not.toContain('plant|delay|payoff|drop')
    expect(prompt).not.toContain('"foreshadow"')
    expect(prompt).not.toContain('"payoff:旧线索名"')
    expect(prompt).not.toContain('"delay:未到时机的线索"')
    expect(prompt).not.toContain('"plant:新线索"')
    expect(prompt).not.toContain('"drop:过期或重复线索"')
    expect(prompt).toContain('剧情目标')
    expect(prompt).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(prompt).toContain('【剧情目标】可能为空')
    expect(prompt).toContain('Director 不得新建、微调、替换剧情目标')
    expect(prompt).toContain('是否替换目标交给 Postprocess 判断')
    expect(prompt).toContain('## 玩家输入')
    expect(prompt).toContain('{{playerInput}}')
    expect(serverSource).toContain("const directorMessages = renderPromptMessagePair('director.md'")
    expect(serverSource).toContain('directorSystem: string')
    expect(serverSource).toContain('const directorUser = directorMessages.user')
    expect(prompt).toContain('JSON 形状')
    expect(serverSource).toContain("promptMessages(directorPayload.directorSystem, directorPayload.directorUser)")
    expect(prompt).not.toContain('"mode": "keep | create | adjust | replace"')
    expect(prompt).not.toContain('"longRangeUpdate"')
    expect(prompt).not.toContain('自行生成第一个当前剧情目标')
    expect(prompt).not.toContain('自行修订当前剧情目标')
    expect(prompt).toContain('玩家意图不是剧情最高目标')
    expect(prompt).toContain('合理阻力')
    expect(prompt).not.toContain('上帝模式导演要求')
    expect(prompt).not.toContain('避免剧情滑向')
    expect(prompt).not.toContain('压缩要求')
    expect(prompt).not.toContain('400-800')
    expect(prompt).not.toContain('`reason`')
    expect(prompt).not.toContain('纯分类索引')
    expect(prompt).not.toContain('"reason"')
    expect(prompt).not.toContain('"editorChecklist"')
    expect(prompt).not.toContain('"targetTextRange"')
    expect(prompt).not.toContain('"beatWordPlan"')
    expect(prompt).not.toContain('"turnIndex"')
    expect(prompt).not.toContain('"povPolicy"')
    expect(prompt).not.toContain('"pov"')
    expect(prompt).not.toContain('"targetWords"')
    expect(prompt).not.toContain('"kind"')
    expect(prompt).not.toContain('"beatId"')
    expect(prompt).not.toContain('"descriptionPlans"')
    expect(prompt).not.toContain('"spatialBlocking"')
    expect(prompt).not.toContain('"stateUpdates"')
    expect(prompt).not.toContain('"neededPostprocess"')
    expect(prompt).not.toContain('"postprocessPlan"')
    expect(prompt).not.toContain('"requirementReinforcement"')
    expect(prompt).not.toContain('"preflight"')
    expect(prompt).not.toContain('"pacing"')
    expect(prompt).not.toContain('"policy"')
    expect(prompt).not.toContain('"craft"')
    expect(prompt).not.toContain('"npc"')
    expect(prompt).not.toContain('"load"')
    expect(prompt).not.toContain('"plotDirection"')
    expect(prompt).not.toContain('follow:当前方向')
    expect(prompt).not.toContain('avoid:不要硬塞')
    expect(prompt).not.toContain('"mustNotResolve"')
    expect(prompt).not.toContain('本轮不能解决的内容')
    expect(prompt).not.toContain('主要NPC情绪和知识边界')
    expect(prompt).not.toContain('"exitWindow"')
    expect(prompt).not.toContain('"brief"')
    expect(prompt).toContain('"goalStep"')
    expect(prompt).toContain('"beat1"')
    expect(prompt).toContain('"beat2"')
    expect(prompt).toContain('"beat3"')
    expect(prompt).toContain('描写链类型')
    expect(prompt).toContain('描写对象')
    expect(prompt).not.toContain('"playerOptions"')
    expect(prompt).not.toContain('推进/靠近')
    expect(prompt).not.toContain('试探/询问')
    expect(prompt).not.toContain('保留/转移')
    expect(prompt).not.toContain('"beats": [')
    expect(serverSource).toContain('function compactDirectorPlan')
    expect(serverSource).toContain('function compactDirectorBeats')
    expect(serverSource).toContain('function derivePlotFromBeats')
    expect(serverSource).toContain('function compactDirectorPlan(value: unknown, fallback: { plotGoal?: unknown } = {})')
    expect(serverSource).toContain('const goalStep = compactText(source.goalStep || derivedPlot || fallback.plotGoal, 160)')
    expect(serverSource).toContain('directorPlan = compactDirectorPlan(director.json, { plotGoal: directorPayload.plotGoal })')
    expect(serverSource).toContain('const explicit = [source.beat1, source.beat2, source.beat3]')
    expect(serverSource).toContain('beat1: beats[0]')
    expect(serverSource).toContain('beat2: beats[1]')
    expect(serverSource).toContain('beat3: beats[2]')
    expect(serverSource).not.toContain('playerOptions: normalizePlayerOptions(source.playerOptions || source.options || source.choices)')
    expect(serverSource).toContain('function extractNarratorPlayerOptions')
    expect(serverSource).not.toContain('beats: compactDirectorBeats(source)')
    expect(serverSource).not.toContain('function runStoryCuratorCall')
    expect(serverSource).not.toContain('shouldRequestStoryCurator')
    expect(serverSource).not.toContain('function compactDescriptionFocus')
    expect(serverSource).not.toContain('directorGuidance')
    expect(serverSource).toContain('JSON.stringify(options.directorPlan)')
    expect(serverSource).not.toContain('currentPhysicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(serverSource).not.toContain('plotState')
    expect(serverSource).not.toContain('jumpToNextPhysicalScene')
    expect(serverSource).not.toContain('physicalSceneSkip')
    expect(serverSource).not.toContain('physicalSceneDecision: compactText')
    expect(serverSource).not.toContain('sceneLimits: compactStringArray')
    expect(serverSource).not.toContain('spatialState')
    expect(serverSource).not.toContain('targetTextRange: compactText')
    expect(serverSource).not.toContain('beatWordPlan: requirement.beatWordPlan')
    expect(serverSource).not.toContain('policy: compactStringArray')
    expect(serverSource).not.toContain('craft: compactStringArray')
    expect(serverSource).not.toContain('source.craft')
    expect(serverSource).not.toContain('npc: compactText')
    expect(serverSource).not.toContain('source.npc')
    expect(serverSource).not.toContain('mainNpcRead')
    expect(serverSource).not.toContain('load: compactStringArray')
    expect(serverSource).not.toContain('source.load')
    expect(serverSource).not.toContain('plotDirection: compactStringArray')
    expect(serverSource).not.toContain('source.plotDirection')
    expect(serverSource).not.toContain('mustNotResolve: compactStringArray')
    expect(serverSource).not.toContain('source.mustNotResolve')
    expect(serverSource).not.toContain('brief: compactText')
    expect(serverSource).not.toContain('source.brief')
    expect(serverSource).not.toContain('narratorBrief')
    expect(serverSource).not.toContain('targetWords:')
    expect(serverSource).not.toContain('kind:')
    expect(serverSource).not.toContain('spatialBlocking:')
    expect(serverSource).not.toContain('stateUpdates:')
    expect(serverSource).not.toContain('postprocessPlan:')
    expect(prompt).not.toContain('sceneLimits')
  })

  it('keeps modular plot construction and description-chain guidance in director', () => {
    const prompt = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('`beat1` / `beat2` / `beat3` 必须全部输出')
    expect(prompt).toContain('氛围模块')
    expect(prompt).toContain('推进模块')
    expect(prompt).toContain('插入模块')
    expect(prompt).toContain('描写链类型：`集中` 或 `转接`')
    expect(prompt).toContain('剧情模块类型｜具体事件梗概｜描写链类型｜描写对象')
    expect(prompt).toContain('剧情模块类型｜具体窗口与未解压力｜描写链类型｜描写对象')
    expect(prompt).toContain('beat 只写简略剧情骨架')
    expect(prompt).toContain('不写小说正文、不写完整对白、不写细节铺陈')
    expect(prompt).toContain('【最近导演计划】只作反重复参照')
    expect(prompt).toContain('`physicalConstraints` 只写本轮纯物理禁止事项')
    expect(narrator).toContain('必须严格按 Director 计划里的 `beat1 -> beat2 -> beat3 -> ending` 顺序组织正文')
    expect(narrator).toContain('不得跳过、合并、倒序')
    expect(narrator).toContain('四项都必须在 `draftText` 中落地')
    expect(narrator).toContain('beat 之间必须有自然过渡')
    expect(narrator).toContain('不得像清单一样逐项硬切')
    expect(narrator).toContain('每轮要有清晰的情绪和局面变化')
  })

  it('keeps director pacing balanced between trivial drag and major-event fast-forward', () => {
    const prompt = readPrompt('prompts/director.md')

    expect(prompt).toContain('每轮必须制造一个有剧情意义的明显变化')
    expect(prompt).toContain('本轮至少推进到这个明显变化成立之后再停')
    expect(prompt).toContain('不直接解决核心悬念')
    expect(prompt).toContain('之前发生过的事情不可重复发生')
    expect(prompt).toContain('按时间顺序推动场景阶段和人物关系发展')
    expect(prompt).toContain('不要连续复用同一种外部装置或桥段')
    expect(prompt).toContain('广播、敲门、来电、震动、路人插话')
    expect(prompt).toContain('停在有剧情意义的新窗口')
    expect(prompt).toContain('不可停在低价值小事确认点')
    expect(prompt).toContain('不复用上轮结尾姿势和句式')
  })

  it('keeps director enforcing character independence and player authority boundaries', () => {
    const prompt = readPrompt('prompts/director.md')

    expect(prompt).toContain('NPC 有独立欲望')
    expect(prompt).toContain('不得无条件顺从玩家')
    expect(prompt).toContain('不因小事大幅改变关系')
    expect(prompt).toContain('操控 NPC')
    expect(prompt).toContain('直接判定成功')
    expect(prompt).toContain('不合理强力手段')
    expect(prompt).toContain('只承接玩家角色可做的部分')
    expect(prompt).toContain('可以控制玩家角色的合理连续行动')
    expect(prompt).toContain('不要在低价值小事上交还输入权')
    expect(prompt).toContain('【玩家输入】视为正文材料中已经启动的动作/话语/意图')
    expect(prompt).toContain('不要把它单独包装成 `beat1` 或任何剧情模块')
    expect(prompt).toContain('`beat1` / `beat2` / `beat3` 必须写玩家输入之后的新变化、新反应或新后果')
  })

  it('keeps plot goal ownership in postprocess', () => {
    const initializer = readPrompt('prompts/initializer.md')
    const director = readPrompt('prompts/director.md')
    const postprocess = readPrompt('prompts/postprocess-feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(initializer).toContain('初始化阶段生成第一条 `plotGoal`')
    expect(initializer).toContain('directorStyle')
    expect(initializer).toContain('narratorStyle')
    expect(initializer).toContain('故事专属导演风格')
    expect(initializer).toContain('故事专属叙事风格')
    expect(initializer).toContain('plotGoal')
    expect(initializer).toContain('`{{user}}` 是玩家操控角色的占位符')
    expect(initializer).toContain('不要在 `statusRoster/statusState` 中同时输出“玩家”和 `{{user}}`')
    expect(initializer).not.toContain('`cast`')
    expect(initializer).toContain('包含玩家角色和若干重要 NPC')
    expect(initializer).toContain('不要只写“玩家”，也不要放太多 NPC')
    expect(serverSource).toContain("if (key === 'user') return '{{user}}'")
    expect(initializer).toContain('未来若干轮要靠近的具体人物关系或事件结果')
    expect(initializer).not.toContain('statusPanelSchema')
    expect(initializer).not.toContain('statusPanel')
    expect(initializer).not.toContain('currentPhysicalEnvironment')
    expect(initializer).not.toContain('normalizedEntries')
    expect(director).toContain('剧情应自然、合理地向【剧情目标】推进')
    expect(director).toContain('不得新建、微调、替换剧情目标')
    expect(director).not.toContain('"completion"')
    expect(postprocess).not.toContain('"plotGoalStatus"')
    expect(postprocess).not.toContain('progressing|completed|impossible')
    expect(postprocess).toContain('未来几轮的发展方向骨架')
    expect(postprocess).not.toContain('drifted')
    expect(postprocess).not.toContain('当前剧情目标')
    expect(fs.existsSync(path.join(process.cwd(), 'prompts/high-level-director.md'))).toBe(false)
    expect(serverSource).toContain('plotGoal:')
    expect(serverSource).not.toContain("renderPromptMessagePair('high-level-director.md'")
    expect(serverSource).not.toContain('function shouldRunLongRangeDirector')
    expect(serverSource).toContain('function inferInitialStoryStyles')
    expect(serverSource).not.toContain("const directorStyle = ''")
    expect(serverSource).not.toContain("const narratorStyle = ''")
    expect(serverSource).not.toContain('longRangeDirectorMaxAgeTurns')
    expect(serverSource).not.toContain('function longRangeDirectorTrigger')
    expect(serverSource).not.toContain('postprocess.json.longRangeStatus')
    expect(serverSource).toContain('function resolvePlotGoalAfterPostprocess')
    expect(serverSource).not.toContain('formatLongRangePlanning(directorPlan.longRangeUpdate')
  })

  it('uses single-text narrator output without paragraph patch fields', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('"draftText"')
    expect(prompt).not.toContain('唯一字段名必须是 `draftText`')
    expect(prompt).not.toContain('不得使用 `text`、`content`、`finalText`')
    expect(prompt).toContain('完整小说正文草稿')
    expect(prompt).toContain('JSON 形状')
    expect(prompt).toContain('"playerOptions"')
    expect(prompt).toContain('必须从正文结尾的自然局面推导')
    expect(prompt).toContain('推进/靠近')
    expect(prompt).toContain('试探/询问')
    expect(prompt).toContain('保留/转移')
    expect(prompt).toContain('`beat1 -> beat2 -> beat3 -> ending`')
    expect(prompt).toContain('`goalStep` 不是独立段落')
    expect(prompt).toContain('根据 Director 的 beat1 / beat2 / beat3 / ending，自行组织正文。不要输出标签。')
    expect(prompt).toContain('写作前在内部检查四项是否齐全')
    expect(prompt).toContain('`ending` 必须是正文最后落点')
    expect(prompt).toContain('beat 之间必须有自然过渡')
    expect(prompt).toContain('不得像清单一样逐项硬切')
    expect(prompt).not.toContain('计划里的 `beats`')
    expect(prompt).toContain('{{playerInput}}')
    expect(serverSource).toContain('narratorSystem: string')
    expect(serverSource).toContain("const narratorMessages = renderPromptMessagePair('narrator.md'")
    expect(serverSource).not.toContain('const hanaSystemPrompt = [')
    expect(serverSource).not.toContain('你的名字叫做Hana（哈娜）')
    expect(serverSource).not.toContain('这些预言是顾客解除梦魇困扰的唯一途径。')
    expect(serverSource).not.toContain('你是虚构小说创作助手。')
    expect(serverSource).not.toContain('你是内容拦截测试助手。')
    expect(serverSource).toContain('const narratorSystem = narratorMessages.system')
    expect(serverSource).toContain('const narratorUser = narratorMessages.user')
    expect(serverSource).not.toContain('narratorMessages.system,\n    narratorMessages.user')
    expect(serverSource).toContain("typeof json.text === 'string'")
    expect(serverSource).toContain("typeof json.content === 'string'")
    expect(serverSource).toContain("typeof json.finalText === 'string'")
    expect(serverSource).toContain('return text.trim()')
    expect(serverSource).toContain("promptMessages(narratorPayload.narratorSystem, narratorPayload.narratorUser)")
    expect(prompt).not.toContain('默认正文 600-900 字')
    expect(prompt).not.toContain('硬上限 900 字')
    expect(prompt).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(prompt).not.toContain('sceneLimits')
    expect(prompt).not.toContain('draftParagraphs')
    expect(prompt).not.toContain('`policy`')
    expect(prompt).not.toContain('`craft`')
    expect(prompt).not.toContain('`npc`')
    expect(prompt).not.toContain('`mustNotResolve`')
    expect(prompt).not.toContain('`brief`')
    expect(serverSource).toContain('narratorMaxTokens')
    expect(serverSource).toContain('const narratorMaxTokens = Number(process.env.NARRATOR_MAX_TOKENS || 12000)')
    expect(serverSource).toContain('maxTokens: narratorMaxTokens')
    expect(serverSource).not.toContain('buildNarratorCacheKey')
  })

  it('keeps narrator free of explicit self-check output', () => {
    const prompt = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('NPC 反应必须符合人设')
    expect(prompt).toContain('位置、姿势')
    expect(prompt).toContain('可以书写玩家角色的轻量连续行为')
    expect(prompt).toContain('不要每个动作都停在“等待玩家输入”')
    expect(prompt).toContain('【玩家输入】是正文的一部分')
    expect(prompt).toContain('不要机械复述')
    expect(prompt).toContain('正文重点写它之后引发的新变化、新反应或新后果')
    expect(prompt).toContain('必须严格按 Director 计划里的 `beat1 -> beat2 -> beat3 -> ending` 顺序组织正文')
    expect(prompt).toContain('beat 之间必须有自然过渡')
    expect(prompt).toContain('不得像清单一样逐项硬切')
    expect(prompt).toContain('每轮要有清晰的情绪和局面变化')
    expect(prompt).toContain('不替玩家做重大承诺、长期决定、剧烈行动、不可逆选择或明确价值表态')
    expect(prompt).not.toContain('输出前静默自修')
    expect(prompt).not.toContain('必须自修一遍')
    expect(prompt).not.toContain('审查意见')
    expect(prompt).not.toContain('draftChecks')
  })

  it('keeps character perception limited and internalizes broad novel craft in narrator', () => {
    const prompt = readPrompt('prompts/narrator.md')

    expect(prompt).toContain('角色不能全知')
    expect(prompt).toContain('不能知道不该知道的设定信息')
    expect(prompt).toContain('感知或推理痕迹')
    expect(prompt).toContain('小说化，具体、可视、可听、可触')
    expect(prompt).toContain('动作、对话、细节和场景压力')
    expect(prompt).toContain('可以在不改变 Director 事件骨架的前提下，补充自然对话')
    expect(prompt).toContain('对话要推进人物反应、关系变化或信息压力')
    expect(prompt).toContain('情绪和局面变化')
    expect(prompt).toContain('语言气质匹配世界观')
    expect(prompt).not.toContain('思想锚点')
    expect(prompt).not.toContain('主题内化')
    expect(prompt).not.toContain('全面小说创作指导')
  })

  it('uses turn zero plus latest seven turns as recent detailed context for director and narrator', () => {
    const director = readPrompt('prompts/director.md')
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')
    const appJs = readPrompt('web/app.js')

    expect(director).toContain('【最近正文】')
    expect(director).toContain('{{recentTurns}}')
    expect(director).toContain('【最近正文】只作已发生细节和阶段顺序参照')
    expect(prompt).toContain('【最近正文】')
    expect(prompt).toContain('反重复参照')
    expect(prompt).toContain('换词复述')
    expect(prompt).toContain('避免固定句式')
    expect(prompt).toContain('上轮已写完的事实')
    expect(prompt).toContain('只能一句带过')
    expect(prompt.indexOf('## 最近正文')).toBeLessThan(prompt.indexOf('## 当前人物状态'))
    expect(prompt.indexOf('## 最近正文')).toBeLessThan(prompt.indexOf('## 世界观'))
    expect(prompt.indexOf('## 玩家输入')).toBeLessThan(prompt.indexOf('## 当前人物状态'))
    expect(prompt.indexOf('## 玩家输入')).toBeLessThan(prompt.indexOf('## 故事叙事风格'))
    expect(prompt.indexOf('## 故事叙事风格')).toBeLessThan(prompt.indexOf('## 当前人物状态'))
    expect(prompt.indexOf('## 当前人物状态')).toBeLessThan(prompt.indexOf('## 世界观'))
    expect(prompt.indexOf('## 最近正文')).toBeLessThan(prompt.indexOf('## 玩家输入'))
    expect(director.indexOf('## 导演风格')).toBeLessThan(director.indexOf('## 世界观'))
    expect(director.indexOf('## 世界观')).toBeLessThan(director.indexOf('## 长期总结'))
    expect(director.indexOf('## 长期总结')).toBeLessThan(director.indexOf('## 剧情目标'))
    expect(director.indexOf('## 剧情目标')).toBeLessThan(director.indexOf('## 当前人物状态'))
    expect(director.indexOf('## 当前人物状态')).toBeLessThan(director.indexOf('## 最近正文'))
    expect(director.indexOf('## 最近正文')).toBeLessThan(director.indexOf('## 最近导演计划'))
    expect(director.indexOf('## 最近导演计划')).toBeLessThan(director.indexOf('## 玩家输入'))
    expect(serverSource).toContain('recentTurns: options.context.recentTurns')
    expect(serverSource).toContain('recentTurns: renderConversation(input.recentTurns)')
    expect(serverSource).toContain('recentTurns: context.recentTurns')
    expect(appJs).toContain('recentTurns: buildRecentTurnsForRequest(playerInput)')
    expect(appJs).toContain('return withOpening.slice(-11)')
    expect(prompt).not.toContain('{{longRangeOutline}}')
    expect(serverSource).toContain('recentDirectorPlans: JSON.stringify(compactRecentDirectorPlans(input.recentDirectorPlans))')
  })

  it('injects banned words into narrator prompt instead of delayed postprocess feedback', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/postprocess-feedback.md')
    const bannedWords = readPrompt('prompts/banned-words.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).toContain('不得无原则迎合玩家')
    expect(prompt).toContain('模板化结尾')
    expect(prompt).toContain('滥用“自然”')
    expect(prompt).toContain('## 禁词表')
    expect(prompt).toContain('{{bannedWords}}')
    expect(prompt).toContain('遵守【禁词表】')
    expect(postprocess).not.toContain('{{bannedWords}}')
    expect(postprocess).not.toContain('【最终正文】是否命中【禁用词】')
    expect(serverSource).toContain("bannedWords: readPrompt('banned-words.md')")
    expect(bannedWords).toContain('- 锁骨')
    expect(bannedWords).toContain('- 指节')
    expect(bannedWords).toContain('禁止使用以下词汇')
    expect(prompt).not.toContain('第一优先：【叙述缺陷规避】')
    expect(prompt).not.toContain('第一优先：【禁库限制】')
    expect(prompt).not.toContain('不是……而是')
    expect(prompt).not.toContain('禁库内容处理痕迹')
  })

  it('keeps narrator free of hard cutoff language', () => {
    const prompt = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(prompt).not.toContain('硬上限')
    expect(prompt).not.toContain('截断')
    expect(serverSource).not.toContain('loadUserConfigDefault')
    expect(serverSource).not.toContain("'default-config.json'")
  })

  it('keeps style prompt files but removes runtime user config injection', () => {
    const serverSource = readPrompt('scripts/web-server.ts')
    const directorTemplate = readPrompt('prompts/导演风格/导演风格模板.md')
    const narratorTemplate = readPrompt('prompts/叙事风格/叙事风格模板.md')

    expect(serverSource).not.toContain('interface UserModule')
    expect(serverSource).not.toContain('type UserModuleStage')
    expect(serverSource).not.toContain("path.join(promptDir, '导演风格')")
    expect(serverSource).not.toContain("path.join(promptDir, '叙事风格')")
    expect(serverSource).not.toContain('user-config-templates')
    expect(serverSource).not.toContain('userConfigTemplateDir')
    expect(serverSource).not.toContain("path.join(promptDir, 'user-config')")
    expect(serverSource).not.toContain('configRoots')
    expect(serverSource).not.toContain('function enforceSingleEnabledStylePerLayer')
    expect(serverSource).not.toContain('styleExclusiveGroup')
    expect(serverSource).not.toContain('function renderModulesForStage')
    expect(serverSource).not.toContain('function renderMergedStyle')
    expect(serverSource).not.toContain('input.userModules')
    expect(serverSource).not.toContain('options.modules')
    expect(serverSource).not.toContain("url.pathname === '/api/modules'")
    expect(serverSource).toContain("const directorStyle = String(input.directorStyle || '').trim() || '（无）'")
    expect(serverSource).toContain("const narratorStyle = String(input.narratorStyle || '').trim() || '（无）'")
    expect(serverSource).not.toContain('directorModules:')
    expect(serverSource).not.toContain('narratorModules:')
    expect(directorTemplate).toContain('layer: "director"')
    expect(directorTemplate).toContain('group: "导演风格"')
    expect(directorTemplate).toContain('enabled: false')
    expect(narratorTemplate).toContain('layer: "narrator"')
    expect(narratorTemplate).toContain('group: "叙事风格"')
    expect(narratorTemplate).toContain('enabled: false')
  })

  it('keeps postprocess split into summary and feedback without touching visible text', () => {
    const summaryPrompt = readPrompt('prompts/postprocess-summary.md')
    const feedbackPrompt = readPrompt('prompts/postprocess-feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(summaryPrompt).toContain('总结器')
    expect(summaryPrompt).toContain('不做质量反馈')
    expect(summaryPrompt).toContain('不改正文')
    expect(summaryPrompt).toContain('"turnSummary"')
    expect(summaryPrompt).toContain('"statusSchemaPatch"')
    expect(summaryPrompt).toContain('"statusRosterPatch"')
    expect(summaryPrompt).toContain('"statusStatePatch"')
    expect(summaryPrompt).toContain('`姿势` 是强制状态字段')
    expect(summaryPrompt).toContain('只写变化字段')
    expect(summaryPrompt).not.toContain('{{storyContext}}')
    expect(summaryPrompt).toContain('{{recentTurns}}')
    expect(summaryPrompt).not.toContain('{{directorPlan}}')
    expect(summaryPrompt).not.toContain('{{recentDirectorPlans}}')
    expect(summaryPrompt).not.toContain('文字细节重复')
    expect(summaryPrompt).not.toContain('剧情设计重复')

    expect(feedbackPrompt).toContain('反馈器')
    expect(feedbackPrompt).toContain('{{storyContext}}')
    expect(feedbackPrompt).toContain('{{historicalSummary}}')
    expect(feedbackPrompt).toContain('{{plotGoal}}')
    expect(feedbackPrompt).toContain('{{recentTurns}}')
    expect(feedbackPrompt).toContain('{{recentDirectorPlans}}')
    expect(feedbackPrompt).toContain('{{directorPlan}}')
    expect(feedbackPrompt).toContain('{{playerFeedback}}')
    expect(feedbackPrompt).toContain('文字细节重复')
    expect(feedbackPrompt).toContain('剧情设计重复')
    expect(feedbackPrompt).toContain('可选扰动源')
    expect(feedbackPrompt).toContain('默认必须为空')
    expect(feedbackPrompt).toContain('默认原样输出【剧情目标】')
    expect(feedbackPrompt).toContain('selectedSceneModules')
    expect(feedbackPrompt).toContain('Director 和 Narrator')
    expect(feedbackPrompt).toContain('{{sceneModuleIndex}}')
    expect(feedbackPrompt).toContain('对照【最近导演计划】和【Director 计划】')
    expect(feedbackPrompt).toContain('未来几轮的发展方向骨架')
    expect(feedbackPrompt).not.toContain('statusSchemaPatch')
    expect(feedbackPrompt).not.toContain('statusStatePatch')
    expect(feedbackPrompt).not.toContain('正反馈')
    expect(feedbackPrompt).not.toContain('违背约束')
    expect(feedbackPrompt).not.toContain('节奏不足')
    expect(feedbackPrompt).not.toContain('导演推进不足')
    expect(feedbackPrompt).not.toContain('导演物理违背')

    expect(serverSource).toContain("renderPromptMessagePair('postprocess-summary.md'")
    expect(serverSource).toContain("renderPromptMessagePair('postprocess-feedback.md'")
    expect(serverSource).toContain('function compactRecentDirectorPlans')
    expect(serverSource).toContain('recentDirectorPlans: JSON.stringify(compactRecentDirectorPlans(options.recentDirectorPlans))')
    expect(serverSource).toContain('sceneModulesContent = selectedSceneModuleContentForInput(input)')
    expect(serverSource).toContain('sceneModulesContent,')
    expect(serverSource).toContain("promptMessages(summaryPayload.postprocessSystem, summaryPayload.postprocessUser)")
    expect(serverSource).toContain("promptMessages(feedbackPayload.postprocessSystem, feedbackPayload.postprocessUser)")
    expect(serverSource).toContain('normalizeTurnSummary(summary.json.turnSummary, finalText)')
    expect(serverSource).toContain('compactText(value.文字细节重复')
    expect(serverSource).toContain('compactText(value.剧情设计重复')
    expect(serverSource).toContain('compactText(value.可选扰动源')
    expect(serverSource).toContain('文字细节重复: feedback.文字细节重复')
    expect(serverSource).toContain('剧情设计重复: feedback.剧情设计重复')
    expect(serverSource).toContain('可选扰动源: feedback.可选扰动源')
    expect(serverSource).toContain("{ stage: 'PostprocessSummary', metrics: summary.metrics }")
    expect(serverSource).toContain("{ stage: 'PostprocessFeedback', metrics: feedbackResult.metrics }")
    expect(serverSource).not.toContain("renderPromptMessagePair('postprocess.md'")
    expect(serverSource).not.toContain('compactText(value.违背约束')
    expect(serverSource).not.toContain('compactText(value.节奏不足')
    expect(serverSource).not.toContain('compactText(value.导演推进不足')
    expect(serverSource).not.toContain('compactText(value.导演物理违背')
    expect(serverSource).not.toContain('buildPostprocessCacheKey')
  })

  it('feeds long-term quality feedback into director and narrator without making director verbose', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).toContain('上轮反重复提醒')
    expect(director).toContain('只是下一轮参考')
    expect(narrator).toContain('上轮反重复提醒')
    expect(narrator).toContain('不要输出反馈内容')
    expect(serverSource).toContain('feedbackText?: string')
    expect(serverSource).not.toContain('feedbackMemory?: Array<Record<string, unknown>>')
    expect(serverSource).toContain('feedbackMemory: options.feedbackMemory')
    expect(serverSource).not.toContain('feedbackMemory: compactText(value.feedbackMemory, 300)')
    expect(serverSource).not.toContain('function normalizeFeedbackMemory')
    expect(director).not.toContain('"intent"')
    expect(narrator).not.toContain('承接 `intent`')
    expect(serverSource).not.toContain('intent:')
    expect(serverSource).not.toContain('logicGuidance: postprocess.json.logicGuidance')
    expect(serverSource).not.toContain('characterUpdates: postprocess.json.characterUpdates')
  })

  it('broadcasts persistent player feedback to all runtime modules without merging it into feedback memory', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/postprocess-feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    for (const prompt of [director, narrator, postprocess]) {
      expect(prompt).toContain('{{playerFeedback}}')
      expect(prompt).toContain('玩家负反馈')
    }
    expect(serverSource).toContain('playerFeedback?: string')
    expect(serverSource).toContain('function normalizePlayerFeedback')
    expect(serverSource).toContain('playerFeedback: normalizePlayerFeedback(input.playerFeedback)')
    expect(serverSource).toContain('playerFeedback: directorPayload.playerFeedback')
    expect(serverSource).toContain('playerFeedback: input.playerFeedback || \'\'')
    expect(serverSource).not.toContain('feedbackMemory: normalizePlayerFeedback')
  })

  it('does not keep a separate physical environment state lane across the pipeline', () => {
    const director = readPrompt('prompts/director.md')
    const narrator = readPrompt('prompts/narrator.md')
    const postprocess = readPrompt('prompts/postprocess-feedback.md')
    const serverSource = readPrompt('scripts/web-server.ts')

    expect(director).not.toContain('currentPhysicalEnvironment')
    expect(director).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(director).toContain('## 上轮物理约束')
    expect(director).toContain('{{previousPhysicalConstraints}}')
    expect(director).toContain('仍然成立的必须继承')
    expect(narrator).toContain('physicalConstraints')
    expect(narrator).toContain('纯物理禁止事项')
    expect(narrator).not.toContain('currentPhysicalEnvironment')
    expect(narrator).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(postprocess).not.toContain('当前物理环境由 Director 输出并由程序直接落盘')
    expect(serverSource).not.toContain('function renderPhysicalEnvironment')
    expect(serverSource).not.toContain('physicalEnvironment: context.physicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironment')
    expect(serverSource).not.toContain('currentPhysicalEnvironmentForbidden')
    expect(serverSource).toContain('physicalConstraints?: unknown')
    expect(serverSource).toContain('function renderPhysicalConstraints')
    expect(serverSource).toContain('previousPhysicalConstraints')
    expect(serverSource).toContain('physicalConstraints: compactStringArray')
    expect(serverSource).not.toContain('jumpToNextPhysicalScene')
  })})
