import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readServerSource(): string {
  return fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
}

describe('provider routing', () => {
  it('allows official DeepSeek, Infron models, Fireworks Priority, Google AI Studio, and Cerebras Qwen by default', () => {
    const source = readServerSource()

    expect(source).toContain("const defaultModel = infronGemini31FlashLiteModel")
    expect(source).toContain("officialDeepSeekV4ProModel")
    expect(source).toContain("officialDeepSeekV4FlashModel")
    expect(source).toContain("infronDeepSeekV4ProModel")
    expect(source).toContain("infronDeepSeekV4FlashModel")
    expect(source).toContain("infronGemini31FlashLiteModel")
    expect(source).toContain("googleAiStudioGemini31FlashLiteModel")
    expect(source).toContain("cerebrasQwenModel")
    expect(source).toContain("fireworksDeepSeekV4ProPriorityModel")
    expect(source).toContain("{ id: officialDeepSeekV4ProModel")
    expect(source).toContain("{ id: officialDeepSeekV4FlashModel")
    expect(source).toContain("{ id: infronDeepSeekV4ProModel")
    expect(source).toContain("{ id: infronDeepSeekV4FlashModel")
    expect(source).toContain("{ id: infronGemini31FlashLiteModel")
    expect(source).toContain("{ id: googleAiStudioGemini31FlashLiteModel")
    expect(source).toContain("{ id: cerebrasQwenModel")
    expect(source).toContain("{ id: fireworksDeepSeekV4ProPriorityModel")
    expect(source).toContain("deepseek/deepseek-v4-pro")
    expect(source).toContain("deepseek/deepseek-v4-flash")
    expect(source).toContain("google/gemini-3.1-flash-lite")
    expect(source).toContain("gemini-3.1-flash-lite")
    expect(source).not.toContain("gemini-3.1-flash-lite-preview")
    expect(source).not.toContain("qwen/qwen3.5-flash-02-23")
    expect(source).not.toContain("gemma-4-uncensored")
  })

  it('routes Infron models through the Infron gateway sorted by throughput', () => {
    const source = readServerSource()

    expect(source).toContain("type ModelProvider = 'deepseek' | 'fireworks' | 'infron' | 'cerebras' | 'google-ai-studio'")
    expect(source).toContain("const defaultInfronBaseUrl = 'https://llm.onerouter.pro/v1'")
    expect(source).toContain('function requestInfronContent')
    expect(source).toContain('provider: {')
    expect(source).toContain("sort: 'throughput'")
    expect(source).toContain('function infronRequestModel')
    expect(source).toContain('model === infronGemini31FlashLiteModel')
    expect(source).toContain("const simpleModel = provider === 'deepseek' ? simpleLayerModel : selectedModel")
    expect(source).toContain('INFRON_API_KEY')
    expect(source).toContain('Infron 上游错误')
    expect(source).toContain('function looksLikeHtmlResponse')
    expect(source).toContain('function describeHtmlGatewayError')
    expect(source).toContain('Infron 网关返回非 JSON')
    expect(source).toContain('Infron 返回非 JSON 内容，无法解析')
    expect(source).toContain('providerSort: \'throughput\'')
  })

  it('routes Cerebras Qwen through Cerebras chat completions', () => {
    const source = readServerSource()

    expect(source).toContain("const cerebrasQwenModel = 'qwen-3-235b-a22b-instruct-2507'")
    expect(source).toContain("const defaultCerebrasBaseUrl = 'https://api.cerebras.ai/v1'")
    expect(source).toContain('function requestCerebrasContent')
    expect(source).toContain('CEREBRAS_API_KEY')
    expect(source).toContain('Cerebras 上游错误')
    expect(source).toContain('max_completion_tokens: maxTokens')
    expect(source).not.toContain('Cerebras_BASE_URL')
  })

  it('routes Google AI Studio Gemini through the official OpenAI-compatible endpoint', () => {
    const source = readServerSource()

    expect(source).toContain("const googleAiStudioGemini31FlashLiteModel = 'gemini-3.1-flash-lite'")
    expect(source).toContain("const defaultGoogleAiStudioBaseUrl = 'https://generativelanguage.googleapis.com/v1beta/openai'")
    expect(source).toContain('function requestGoogleAiStudioContent')
    expect(source).toContain('GEMINI_API_KEY')
    expect(source).toContain('GOOGLE_AI_STUDIO_API_KEY')
    expect(source).toContain('Google AI Studio 上游错误')
    expect(source).toContain("provider === 'google-ai-studio'")
  })

  it('routes Fireworks DeepSeek V4 Pro through Fireworks chat completions', () => {
    const source = readServerSource()

    expect(source).toContain('accounts/fireworks/models/deepseek-v4-pro')
    expect(source).toContain('accounts/fireworks/models/deepseek-v4-pro:priority')
    expect(source).toContain('api.fireworks.ai/inference/v1')
    expect(source).toContain('function requestFireworksContent')
    expect(source).toContain('FIREWORKS_API_KEY')
    expect(source).toContain('Fireworks API Key')
    expect(source).toContain('Fireworks 上游错误')
    expect(source).not.toContain('stream_options')
    expect(source).not.toContain('function readFireworksStream')
    expect(source).not.toContain('choice.delta?.content')
    expect(source).toContain('choices?: Array<{ message?: { content?: string } }>')
    expect(source).toContain('const raw = payload.choices?.[0]?.message?.content?.trim()')
    expect(source).toContain('service_tier')
    expect(source).toContain("service_tier: 'priority'")
    expect(source).toContain('fireworksDeepSeekV4ProRequestModel')
    expect(source).not.toContain('function fireworksRequestModel')
    expect(source).not.toContain('function fireworksServiceTier')
    expect(source).toContain('x-session-affinity')
    expect(source).not.toContain('const streamed = await readFireworksStream')
    expect(source).not.toContain('FIREWORKS_STREAM_IDLE_TIMEOUT_MS')
    expect(source).not.toContain('function readFireworksChunkWithIdleTimeout')
    expect(source).toContain('if (isAbortError(error))')
    expect(source).toContain('function fetchWithTransientRetry')
    expect(source).toContain('LLM_FETCH_RETRY_COUNT')
    expect(source).toContain('Fireworks 网络请求失败')
    expect(source.indexOf('const text = await response.text()')).toBeLessThan(source.indexOf('clearTimeout(timer)', source.indexOf('function requestFireworksContent')))
  })

  it('does not let long range director block a completed turn', () => {
    const source = readServerSource()

    expect(source).toContain("label: 'LongRangeDirector'")
    expect(source).toContain('LONG_RANGE_DIRECTOR_TIMEOUT_MS')
    expect(source).toContain('maxTokens: 1200')
    expect(source).toContain('timeoutMs: longRangeDirectorTimeoutMs')
    expect(source).toContain('超过 ${Math.round(Number(options.timeoutMs) / 1000)} 秒未完成')
    expect(source).toContain("type: 'stage_skip'")
    expect(source).toContain('高级导演层未返回，已跳过以免阻塞本轮')
  })

  it('bounds foreground narrator calls instead of waiting for the global provider timeout', () => {
    const source = readServerSource()

    expect(source).toContain('NARRATOR_TIMEOUT_MS')
    expect(source).toContain('timeoutMs: narratorTimeoutMs')
    expect(source).toContain('Narrator')
  })

  it('exposes a small provider connectivity probe', () => {
    const source = readServerSource()

    expect(source).toContain('interface ProviderTestRequest')
    expect(source).toContain("url.pathname === '/api/provider-test'")
    expect(source).toContain('async function testProvider')
    expect(source).toContain('providerApiKey(provider, input.apiKey)')
    expect(source).toContain('requestModelContent(apiKey')
    expect(source).toContain('ProviderTest')
    expect(source).toContain('providerConnectivityTimeoutMs')
    expect(source).toContain('30_000')
    const connectivityBody = source.slice(source.indexOf('async function testProvider'), source.indexOf('async function testProviderSpeed'))
    expect(connectivityBody).not.toContain('usage:')
    expect(connectivityBody).not.toContain('reply:')
  })

  it('exposes a streamed provider speed probe with real TTFT and TPS', () => {
    const source = readServerSource()

    expect(source).toContain('interface ProviderSpeedTestRequest')
    expect(source).toContain("url.pathname === '/api/provider-speed-test'")
    expect(source).toContain('async function testProviderSpeed')
    expect(source).toContain('function requestModelStreamProbe')
    expect(source).toContain('function extractStreamDelta')
    expect(source).toContain('function appendSpeedTestRecord')
    expect(source).toContain("const speedTestRecordFile = path.join(docsDir, '模型速度测试记录.md')")
    expect(source).toContain('stream: true')
    expect(source).toContain('providerSpeedTestTimeoutMs')
    expect(source).toContain('100_000')
    expect(source).toContain('约 1200 个汉字')
    expect(source).toContain('firstTokenAt ? firstTokenAt - startedAt : durationMs')
    expect(source).toContain('generationMs = Math.max(1, result.metrics.durationMs - (result.metrics.ttftMs || 0))')
    expect(source).toContain('appendSpeedTestRecord({')
    expect(source).toContain('recordFile: path.relative(rootDir, speedTestRecordFile)')
    expect(source).toContain("const defaultPromptProfile = '繁花'")
    expect(source).toContain("url.pathname === '/api/prompt-profile'")
    expect(source).toContain('writeActivePromptProfile(promptProfile)')
  })

  it('writes per-game pipeline speed records beside saves', () => {
    const source = readServerSource()

    expect(source).toContain("const speedRecordsDir = path.join(saveDir, 'speed-records')")
    expect(source).toContain('function speedRecordFileForGame')
    expect(source).toContain('function appendPipelineSpeedRecord')
    expect(source).toContain('storyId?: string')
    expect(source).toContain('storyName?: string')
    expect(source).toContain('appendPipelineSpeedRecord({')
    expect(source).toContain("mode: 'generate'")
    expect(source).toContain("mode: 'postprocess-retry'")
    expect(source).toContain("stage: 'Director'")
    expect(source).toContain("stage: 'Narrator'")
    expect(source).toContain("stage: 'Postprocess'")
    expect(source).toContain('无法测真实 TTFT/TPS')
    expect(source).toContain('输出tokens/秒(总耗时估算)')
    expect(source).toContain('function metricTtftDisplay')
    expect(source).toContain('function metricOutputTokensPerSecondEstimate')
    expect(source).not.toContain('function metricTps')
    expect(source).toContain('speedRecordFile')
  })

  it('can snapshot the current Narrator prompt and run raw interception tests', () => {
    const source = readServerSource()

    expect(source).toContain('interface InterceptionPromptRequest')
    expect(source).toContain('interface InterceptionTestRequest')
    expect(source).toContain("const interceptionDebugDir = path.join(debugDir, 'content-interception')")
    expect(source).toContain("url.pathname === '/api/content-interception/prompt'")
    expect(source).toContain("url.pathname === '/api/content-interception/test'")
    expect(source).toContain('function buildInterceptionNarratorPrompt')
    expect(source).toContain('function runInterceptionTest')
    expect(source).toContain('缺少测试 Prompt，请先生成快照或选择 Prompt 文件。')
    expect(source).toContain('requestModelContent(apiKey, messages')
    expect(source).toContain('interception-test-request')
    expect(source).toContain('interception-test-response')
    expect(source).not.toContain('callModel(messages, { temperature: Number.isFinite(input.temperature)')
  })

  it('does not use official DeepSeek JSON mode because it can return empty content', () => {
    const source = readServerSource()
    const deepSeekBody = source.slice(source.indexOf('async function requestDeepSeekContent'), source.indexOf('async function requestFireworksContent'))

    expect(source).toContain("label: `${label}-deepseek-empty`")
    expect(source).toContain('finish_reason')
    expect(source).toContain('DeepSeek returned an empty response${reasonText}；原始返回已保存')
    expect(source).toContain('const defaultMaxTokens = Number(process.env.LLM_MAX_TOKENS || 8192)')
    expect(deepSeekBody).not.toContain('response_format')
    expect(deepSeekBody).not.toContain('json_object')
  })

  it('uses Infron throughput routing without reasoning or forced JSON mode', () => {
    const source = readServerSource()
    const infronBody = source.slice(source.indexOf('async function requestInfronContent'), source.indexOf('async function requestCerebrasContent'))

    expect(infronBody).toContain("sort: 'throughput'")
    expect(infronBody).not.toContain('reasoning')
    expect(infronBody).not.toContain('effort')
    expect(infronBody).not.toContain('response_format')
    expect(source).not.toContain("type: 'json_schema'")
    expect(source).not.toContain('structuredJson')
  })

  it('keeps request types compact through a shared pipeline context', () => {
    const source = readServerSource()

    expect(source).toContain('interface PipelineContext')
    expect(source).toContain('interface GenerateRequest extends PipelineContext')
    expect(source).toContain('interface PostprocessRequest extends PipelineContext')
    expect(source).not.toContain('interface EvaluationRequest')
  })

  it('bounds director calls so regeneration cannot hang forever', () => {
    const source = readServerSource()

    expect(source).toContain('DIRECTOR_TIMEOUT_MS')
    expect(source).toContain('const directorTimeoutMs = Number(process.env.DIRECTOR_TIMEOUT_MS || 300_000)')
    expect(source).toContain('DIRECTOR_MAX_TOKENS')
    expect(source).toContain('const directorMaxTokens = Number(process.env.DIRECTOR_MAX_TOKENS || 2000)')
    expect(source).toContain('const directorTemperature = Math.min(temperature, 0.4)')
    expect(source).toContain('timeoutMs: directorTimeoutMs')
    expect(source).toContain('maxTokens: directorMaxTokens')
    expect(source).toContain('temperature: directorTemperature')
    expect(source).toContain("label: `${label}-timeout`")
    expect(source).toContain('Director')
    expect(source).toContain('超过 ${Math.round(Number(options.timeoutMs) / 1000)} 秒未完成')
  })

  it('routes DeepSeek and Infron postprocess through official DeepSeek Flash', () => {
    const source = readServerSource()

    expect(source).toContain('const strongLayerModel = officialDeepSeekV4ProModel')
    expect(source).toContain('const simpleLayerModel = officialDeepSeekV4FlashModel')
    expect(source).toContain("const provider = providerForModel(normalizeModel(requestedModel))")
    expect(source).toContain("const strongModel = provider === 'deepseek' ? strongLayerModel : selectedModel")
    expect(source).toContain("const simpleModel = provider === 'deepseek' ? simpleLayerModel : selectedModel")
    expect(source).toContain('function pipelineApiKeyForModel')
    expect(source).toContain('const keyed = input.apiKeys?.[provider]')
    expect(source).toContain('const pipelineModels = buildPipelineModels(requestedModel)')
    expect(source).toContain('const narratorModel = pipelineModels.narrator')
    expect(source).toContain('const postprocessModel = pipelineModels.postprocess')
    expect(source).toContain('const longRangeDirectorModel = pipelineModels.longRangeDirector')
    expect(source).toContain('model: directorModel')
    expect(source).toContain('model: narratorModel')
    expect(source).toContain('model: postprocessModel')
    expect(source).toContain('model: longRangeDirectorModel')
    expect(source).toContain('pipelineModels: buildPipelineModels()')
  })
})
