import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'

function readServerSource(): string {
  return fs.readFileSync(path.join(process.cwd(), 'scripts/web-server.ts'), 'utf-8')
}

describe('provider routing', () => {
  it('allows official DeepSeek, Infron models, Fireworks Priority, Google AI Studio, and Cerebras Qwen by default', () => {
    const source = readServerSource()

    expect(source).toContain("const defaultModel = officialDeepSeekV4FlashModel")
    expect(source).toContain("officialDeepSeekV4ProModel")
    expect(source).toContain("officialDeepSeekV4FlashModel")
    expect(source).toContain("infronDeepSeekV4ProModel")
    expect(source).toContain("infronDeepSeekV4FlashModel")
    expect(source).toContain("infronGemini31FlashLiteModel")
    expect(source).toContain("infronGemini25FlashModel")
    expect(source).toContain("infronGemini3FlashPreviewModel")
    expect(source).toContain("infronKimiK25Model")
    expect(source).toContain("infronQwen35EaricaModel")
    expect(source).toContain("infronQwen36FlashModel")
    expect(source).toContain("infronQwen36PlusModel")
    expect(source).toContain("infronXiaomiMimo25Model")
    expect(source).toContain("infronGlm47FlashxModel")
    expect(source).toContain("infronGlm51Model")
    expect(source).toContain("infronGrok43Model")
    expect(source).toContain("googleAiStudioGemini31FlashLiteModel")
    expect(source).toContain("cerebrasQwenModel")
    expect(source).toContain("fireworksDeepSeekV4ProPriorityModel")
    expect(source).toContain("fireworksKimiK2P5Model")
    expect(source).toContain("fireworksQwen3235BA22BModel")
    expect(source).toContain("fireworksQwen36PlusModel")
    expect(source).not.toContain("fireworksGemma431BItModel")
    expect(source).not.toContain("fireworksDeepSeekV3P2Model")
    expect(source).toContain("{ id: officialDeepSeekV4ProModel")
    expect(source).toContain("{ id: officialDeepSeekV4FlashModel")
    expect(source).toContain("{ id: infronDeepSeekV4ProModel")
    expect(source).toContain("{ id: infronDeepSeekV4FlashModel")
    expect(source).toContain("{ id: infronGemini31FlashLiteModel")
    expect(source).toContain("{ id: infronGemini25FlashModel")
    expect(source).toContain("{ id: infronGemini3FlashPreviewModel")
    expect(source).toContain("{ id: infronKimiK25Model")
    expect(source).toContain("{ id: infronQwen35EaricaModel")
    expect(source).toContain("{ id: infronQwen36FlashModel")
    expect(source).toContain("{ id: infronQwen36PlusModel")
    expect(source).toContain("{ id: infronXiaomiMimo25Model")
    expect(source).toContain("{ id: infronGlm47FlashxModel")
    expect(source).toContain("{ id: infronGlm51Model")
    expect(source).toContain("{ id: infronGrok43Model")
    expect(source).toContain("{ id: googleAiStudioGemini31FlashLiteModel")
    expect(source).toContain("{ id: cerebrasQwenModel")
    expect(source).toContain("{ id: fireworksDeepSeekV4ProPriorityModel")
    expect(source).toContain("{ id: fireworksKimiK2P5Model")
    expect(source).toContain("{ id: fireworksQwen3235BA22BModel")
    expect(source).toContain("{ id: fireworksQwen36PlusModel")
    expect(source).toContain("deepseek/deepseek-v4-pro")
    expect(source).toContain("deepseek/deepseek-v4-flash")
    expect(source).toContain("google/gemini-3.1-flash-lite")
    expect(source).toContain("google/gemini-2.5-flash")
    expect(source).toContain("google/gemini-3-flash-preview")
    expect(source).toContain("moonshotai/kimi-k2.5")
    expect(source).toContain("qwen/qwen3.5-27b-earica-derestricted")
    expect(source).toContain("qwen/qwen3.6-flash")
    expect(source).toContain("qwen/qwen3.6-plus")
    expect(source).toContain("xiaomi/mimo-v2.5")
    expect(source).toContain("z-ai/glm-4.7-flashx")
    expect(source).toContain("z-ai/glm-5.1")
    expect(source).toContain("x-ai/grok-4.3")
    expect(source).toContain("gemini-3.1-flash-lite")
    expect(source).toContain("accounts/fireworks/models/kimi-k2p5")
    expect(source).toContain("accounts/fireworks/models/qwen3-235b-a22b")
    expect(source).toContain("accounts/fireworks/models/qwen3p6-plus")
    expect(source).not.toContain("accounts/fireworks/models/gemma-4-31b-it")
    expect(source).not.toContain("accounts/fireworks/models/deepseek-v3p2")
    expect(source).not.toContain("gemini-3.1-flash-lite-preview")
    expect(source).not.toContain("qwen/qwen3.5-flash-02-23")
    expect(source).not.toContain("gemma-4-uncensored")
  })

  it('routes Infron models through the Infron gateway sorted by throughput', () => {
    const source = readServerSource()

    expect(source).toContain("type ModelProvider = 'deepseek' | 'fireworks' | 'infron' | 'cerebras' | 'google-ai-studio'")
    expect(source).toContain("const defaultInfronBaseUrl = 'https://llm.onerouter.pro/v1'")
    expect(source).toContain('function requestInfronContent')
    expect(source).toContain('provider: {')
    expect(source).toContain("sort: 'throughput'")
    expect(source).not.toContain('function infronRequestModel')
    expect(source).toContain('model === infronGemini31FlashLiteModel')
    expect(source).toContain('const selectedModel = normalizeModel(requestedModel)')
    expect(source).toContain('INFRON_API_KEY')
    expect(source).toContain('Infron 上游错误')
    expect(source).toContain('function looksLikeHtmlResponse')
    expect(source).toContain('function describeHtmlGatewayError')
    expect(source).toContain('Infron 网关返回非 JSON')
    expect(source).toContain('Infron 返回非 JSON 内容，无法解析')
    expect(source).toContain('providerSort: \'throughput\'')
  })

  it('routes Cerebras Qwen through Cerebras chat completions', () => {
    const source = readServerSource()

    expect(source).toContain("const cerebrasQwenModel = 'qwen-3-235b-a22b-instruct-2507'")
    expect(source).toContain("const defaultCerebrasBaseUrl = 'https://api.cerebras.ai/v1'")
    expect(source).toContain('function requestCerebrasContent')
    expect(source).toContain('CEREBRAS_API_KEY')
    expect(source).toContain('Cerebras 上游错误')
    expect(source).toContain('max_completion_tokens: maxTokens')
    expect(source).not.toContain('Cerebras_BASE_URL')
  })

  it('routes Google AI Studio Gemini through the official OpenAI-compatible endpoint', () => {
    const source = readServerSource()

    expect(source).toContain("const googleAiStudioGemini31FlashLiteModel = 'gemini-3.1-flash-lite'")
    expect(source).toContain("const defaultGoogleAiStudioBaseUrl = 'https://generativelanguage.googleapis.com/v1beta/openai'")
    expect(source).toContain('function requestGoogleAiStudioContent')
    expect(source).toContain('GEMINI_API_KEY')
    expect(source).toContain('GOOGLE_AI_STUDIO_API_KEY')
    expect(source).toContain('Google AI Studio 上游错误')
    expect(source).toContain("provider === 'google-ai-studio'")
  })

  it('routes Fireworks DeepSeek V4 Pro through Fireworks chat completions', () => {
    const source = readServerSource()

    expect(source).toContain('accounts/fireworks/models/deepseek-v4-pro')
    expect(source).toContain('accounts/fireworks/models/deepseek-v4-pro:priority')
    expect(source).toContain('api.fireworks.ai/inference/v1')
    expect(source).toContain('function requestFireworksContent')
    expect(source).toContain('FIREWORKS_API_KEY')
    expect(source).toContain('Fireworks API Key')
    expect(source).toContain('Fireworks 上游错误')
    expect(source).not.toContain('stream_options')
    expect(source).not.toContain('function readFireworksStream')
    expect(source).not.toContain('choice.delta?.content')
    expect(source).toContain('choices?: Array<{ message?: { content?: string } }>')
    expect(source).toContain('const raw = payload.choices?.[0]?.message?.content?.trim()')
    expect(source).toContain('service_tier')
    expect(source).toContain("body.service_tier = 'priority'")
    expect(source).toContain('model === fireworksDeepSeekV4ProPriorityModel || model === fireworksKimiK2P5Model')
    expect(source).toContain('fireworksDeepSeekV4ProRequestModel')
    expect(source).toContain('function fireworksRequestModel')
    expect(source).toContain('function applyFireworksPriority')
    expect(source).not.toContain('function fireworksServiceTier')
    expect(source).toContain('x-session-affinity')
    expect(source).not.toContain('const streamed = await readFireworksStream')
    expect(source).not.toContain('FIREWORKS_STREAM_IDLE_TIMEOUT_MS')
    expect(source).not.toContain('function readFireworksChunkWithIdleTimeout')
    expect(source).toContain('if (isAbortError(error))')
    expect(source).toContain('function fetchWithTransientRetry')
    expect(source).toContain('LLM_FETCH_RETRY_COUNT')
    expect(source).toContain('Fireworks 网络请求失败')
    expect(source.indexOf('const text = await response.text()')).toBeLessThan(source.indexOf('clearTimeout(timer)', source.indexOf('function requestFireworksContent')))
  })

  it('does not keep a long range director layer', () => {
    const source = readServerSource()

    expect(source).not.toContain("label: 'LongRangeDirector'")
    expect(source).not.toContain('LONG_RANGE_DIRECTOR_TIMEOUT_MS')
    expect(source).not.toContain('longRangeDirectorTimeoutMs')
  })

  it('bounds foreground narrator calls instead of waiting for the global provider timeout', () => {
    const source = readServerSource()

    expect(source).toContain('NARRATOR_TIMEOUT_MS')
    expect(source).toContain('timeoutMs: narratorTimeoutMs')
    expect(source).toContain('Narrator')
  })

  it('keeps LLM response body reads under the provider timeout', () => {
    const source = readServerSource()

    expect(source).toContain('async function readResponseTextWithTimeout')
    expect(source).toContain('return await response.text()')
    expect(source).toContain('clearTimeout(timer)')
    expect(source).toContain('readResponseTextWithTimeout(response, controller, timer, unlinkAbortSignal)')
  })

  it('bounds postprocess calls with a dedicated timeout', () => {
    const source = readServerSource()

    expect(source).toContain('POSTPROCESS_TIMEOUT_MS')
    expect(source).toContain('const postprocessTimeoutMs')
    expect(source).toContain('timeoutMs: postprocessTimeoutMs')
  })

  it('exposes a small provider connectivity probe', () => {
    const source = readServerSource()

    expect(source).toContain('interface ProviderTestRequest')
    expect(source).toContain("url.pathname === '/api/provider-test'")
    expect(source).toContain('async function testProvider')
    expect(source).toContain('providerApiKey(provider, input.apiKey)')
    expect(source).toContain('requestModelContent(apiKey')
    expect(source).toContain('ProviderTest')
    expect(source).toContain('providerConnectivityTimeoutMs')
    expect(source).toContain('30_000')
    const connectivityBody = source.slice(source.indexOf('async function testProvider'), source.indexOf('async function testProviderSpeed'))
    expect(connectivityBody).not.toContain('usage:')
    expect(connectivityBody).not.toContain('reply:')
  })

  it('exposes a streamed provider speed probe with real TTFT and TPS', () => {
    const source = readServerSource()

    expect(source).toContain('interface ProviderSpeedTestRequest')
    expect(source).toContain("url.pathname === '/api/provider-speed-test'")
    expect(source).toContain('async function testProviderSpeed')
    expect(source).toContain('function requestModelStreamProbe')
    expect(source).toContain('function extractStreamDelta')
    expect(source).toContain('function appendSpeedTestRecord')
    expect(source).toContain("const speedTestRecordFile = path.join(docsDir, '模型速度测试记录.md')")
    expect(source).toContain('stream: true')
    expect(source).toContain('providerSpeedTestTimeoutMs')
    expect(source).toContain('100_000')
    expect(source).toContain('约 1200 个汉字')
    expect(source).toContain('firstTokenAt ? firstTokenAt - startedAt : durationMs')
    expect(source).toContain('generationMs = Math.max(1, result.metrics.durationMs - (result.metrics.ttftMs || 0))')
    expect(source).toContain('appendSpeedTestRecord({')
    expect(source).toContain('recordFile: path.relative(rootDir, speedTestRecordFile)')
    expect(source).not.toContain("url.pathname === '/api/prompt-profile'")
    expect(source).not.toContain('writeActivePromptProfile')
  })

  it('writes per-game pipeline speed records beside saves', () => {
    const source = readServerSource()

    expect(source).toContain("const speedRecordsDir = path.join(saveDir, 'speed-records')")
    expect(source).toContain('function speedRecordFileForGame')
    expect(source).toContain('function appendPipelineSpeedRecord')
    expect(source).toContain('storyId?: string')
    expect(source).toContain('storyName?: string')
    expect(source).toContain('appendPipelineSpeedRecord({')
    expect(source).toContain("mode: 'generate'")
    expect(source).toContain("mode: 'postprocess-retry'")
    expect(source).toContain("stage: 'Director'")
    expect(source).toContain("stage: 'Narrator'")
    expect(source).toContain("stage: 'PostprocessSummary'")
    expect(source).toContain("stage: 'PostprocessFeedback'")
    expect(source).toContain('无法测真实 TTFT/TPS')
    expect(source).toContain('输出tokens/秒(总耗时估算)')
    expect(source).toContain('function metricTtftDisplay')
    expect(source).toContain('function metricOutputTokensPerSecondEstimate')
    expect(source).not.toContain('function metricTps')
    expect(source).toContain('speedRecordFile')
  })

  it('can snapshot the current Narrator prompt and run raw interception tests', () => {
    const source = readServerSource()

    expect(source).toContain('interface InterceptionPromptRequest')
    expect(source).toContain('interface InterceptionTestRequest')
    expect(source).toContain("const interceptionDebugDir = path.join(debugDir, 'content-interception')")
    expect(source).toContain("url.pathname === '/api/content-interception/prompt'")
    expect(source).toContain("url.pathname === '/api/content-interception/test'")
    expect(source).toContain('function buildInterceptionNarratorPrompt')
    expect(source).toContain('function runInterceptionTest')
    expect(source).toContain('缺少测试 Prompt，请先生成快照或选择 Prompt 文件。')
    expect(source).toContain('requestModelContent(apiKey, messages')
    expect(source).toContain('interception-test-request')
    expect(source).toContain('interception-test-response')
    expect(source).not.toContain('callModel(messages, { temperature: Number.isFinite(input.temperature)')
  })

  it('does not use official DeepSeek JSON mode because it can return empty content', () => {
    const source = readServerSource()
    const deepSeekBody = source.slice(source.indexOf('async function requestDeepSeekContent'), source.indexOf('async function requestFireworksContent'))

    expect(source).toContain("label: `${label}-deepseek-empty`")
    expect(source).toContain('finish_reason')
    expect(source).toContain('DeepSeek returned an empty response${reasonText}；原始返回已保存')
    expect(source).toContain('const defaultMaxTokens = Number(process.env.LLM_MAX_TOKENS || 8192)')
    expect(deepSeekBody).not.toContain('response_format')
    expect(deepSeekBody).not.toContain('json_object')
  })

  it('uses Infron throughput routing with optional reasoning and without forced JSON mode', () => {
    const source = readServerSource()
    const infronBody = source.slice(source.indexOf('async function requestInfronContent'), source.indexOf('async function requestCerebrasContent'))

    expect(source).toContain("const infronReasoningEfforts = new Set(['none', 'low', 'medium', 'high'])")
    expect(source).toContain('function applyInfronReasoning')
    expect(source).toContain('if (normalized) body.reasoning = { effort: normalized }')
    expect(infronBody).toContain("sort: 'throughput'")
    expect(infronBody).toContain('reasoning')
    expect(infronBody).toContain('applyInfronReasoning(body, reasoningEffort)')
    expect(source).not.toContain('infronReasoningHeavyModels')
    expect(source).toContain('function infronMaxTokensForModel')
    expect(source).toContain('model === infronXiaomiMimo25Model')
    expect(source).toContain('return Math.max(maxTokens, infronReasoningMinMaxTokens)')
    expect(source).not.toContain('infronForceNoReasoningModels')
    expect(infronBody).not.toContain('response_format')
    expect(source).not.toContain("type: 'json_schema'")
    expect(source).not.toContain('structuredJson')
  })

  it('keeps request types compact through a shared pipeline context', () => {
    const source = readServerSource()

    expect(source).toContain('interface PipelineContext')
    expect(source).toContain('interface GenerateRequest extends PipelineContext')
    expect(source).toContain('interface PostprocessRequest extends PipelineContext')
    expect(source).not.toContain('interface EvaluationRequest')
  })

  it('bounds director calls so regeneration cannot hang forever', () => {
    const source = readServerSource()

    expect(source).toContain('DIRECTOR_TIMEOUT_MS')
    expect(source).toContain('const directorTimeoutMs = Number(process.env.DIRECTOR_TIMEOUT_MS || 300_000)')
    expect(source).toContain('DIRECTOR_MAX_TOKENS')
    expect(source).toContain('const directorMaxTokens = Number(process.env.DIRECTOR_MAX_TOKENS || 2000)')
    expect(source).toContain('const directorTemperature = Math.min(temperature, 0.4)')
    expect(source).toContain('timeoutMs: directorTimeoutMs')
    expect(source).toContain('maxTokens: directorMaxTokens')
    expect(source).toContain('temperature: directorTemperature')
    expect(source).toContain("label: `${label}-timeout`")
    expect(source).toContain('Director')
    expect(source).toContain('超过 ${Math.round(Number(options.timeoutMs) / 1000)} 秒未完成')
  })

  it('uses the selected model for every pipeline stage', () => {
    const source = readServerSource()

    expect(source).not.toContain('strongLayerModel')
    expect(source).not.toContain('simpleLayerModel')
    expect(source).toContain('const selectedModel = normalizeModel(requestedModel)')
    expect(source).toContain('director: selectedModel')
    expect(source).toContain('narrator: selectedModel')
    expect(source).toContain('postprocess: selectedModel')
    expect(source).toContain('initializer: selectedModel')
    expect(source).toContain('function pipelineApiKeyForModel')
    expect(source).toContain('const keyed = input.apiKeys?.[provider]')
    expect(source).toContain('const pipelineModels = buildPipelineModels(requestedModel)')
    expect(source).toContain('const narratorModel = pipelineModels.narrator')
    expect(source).toContain('const postprocessModel = pipelineModels.postprocess')
    expect(source).toContain('model: directorModel')
    expect(source).toContain('model: narratorModel')
    expect(source).toContain('model: postprocessModel')
    expect(source).toContain('pipelineModels: buildPipelineModels()')
  })

  it('sets explicit max-token budgets for initializer and postprocess', () => {
    const source = readServerSource()

    expect(source).toContain('const initializerMaxTokens = Number(process.env.INITIALIZER_MAX_TOKENS || defaultMaxTokens)')
    expect(source).toContain('const postprocessMaxTokens = Number(process.env.POSTPROCESS_MAX_TOKENS || defaultMaxTokens)')
    expect(source).toContain('maxTokens: initializerMaxTokens')
    expect(source).toContain('maxTokens: postprocessMaxTokens')
    expect(source).toContain('timeoutMs: postprocessTimeoutMs')
  })
})
